"""Central Simplified Chinese and English user-interface strings."""

DEFAULT_LANGUAGE = "zh_CN"
SUPPORTED_LANGUAGES = ("zh_CN", "en")

ZH_CN = {
    "settings_title": "petoken · 设置", "save": "保存", "cancel": "取消",
    "language": "界面语言", "language_zh_CN": "简体中文", "language_en": "English",
    "task_auto": "自动跟随当前任务", "task_unnamed": "未命名任务",
    "task_selection": "跟随 / 固定任务", "token_scope": "Token 与费用范围",
    "reset_defaults": "恢复默认设置", "confirm_reset": "再次点击确认重置",
    "token_number_format": "Token 数字格式", "token_format_full": "完整数字",
    "token_format_compact": "紧凑格式", "manual_fx": "手动汇率（取消后使用加拿大央行）",
    "custom_price": "覆盖当前模型的 Standard 单价", "model_unrecorded": "模型尚未记录",
    "price_input": "普通输入", "price_cached": "缓存输入", "price_write": "缓存写入",
    "price_output": "输出（含 reasoning）",
    "about_data": "关于数据",
    "about_1_title": "费用估算",
    "about_1_body": "显示的是 API 等价费用估算，不代表 ChatGPT / Codex 或 Claude 订阅的实际扣费。",
    "about_2_title": "Token 统计",
    "about_2_body": "数据来自本地可读取的 Codex 和 Claude Code 记录。缓存、Context 等根据现有记录计算；缺失记录时，结果可能只是部分统计，且不包含工具调用费用。",
    "about_3_title": "模型与推理强度",
    "about_3_body": "模型和 reasoning 通常以会话首次记录的配置为准。通过启动器或会话中途修改的设置，不一定会被完整记录。",
    "about_4_title": "状态与隐私",
    "about_4_body": "状态优先级：Codex / Claude Code 工作 ＞ 麦克风 ＞ 音乐 ＞ 打字 ＞ 待机。浮窗会跟随桌宠展开。Petoken 不保存你输入的按键内容，也不会持久化保存媒体字幕内容。",
    "settings_save_error": "无法保存设置，请检查用户文件夹的写入权限。",
    "scope_global": "全局", "scope_global_recorded": "全局（本地记录）",
    "scope_project": "项目", "scope_conversation": "会话",
    "spirit_accessible": "冰晶小精灵", "connecting": "正在连接…",
    "collapse_expand": "收起 / 展开", "hide_to_tray": "隐藏到系统托盘",
    "waiting_codex": "等待任务", "open_codex_task": "打开 Codex 中的任务",
    "total_tokens": "TOTAL TOKENS", "input": "INPUT", "output": "OUTPUT",
    "switch_scope": "切换统计范围", "analytics_button": "Token Analytics  ↗",
    "analytics_button_tip": "展开完整原始用量、派生指标、模型、会话与历史",
    "context_used": "Context 已用", "five_hour_limit": "5 小时限额",
    "weekly_limit": "每周限额", "estimated_cost": "预估费用",
    "currency": "货币", "fx_unavailable_usd": "汇率暂不可用；以 USD 显示。",
    "one_usd_equals": "1 USD = {rate} {currency}",
    "partial_estimate": "部分估算", "always_on_top": "始终置顶",
    "character_size": "角色大小",
    "star_ring_enabled": "显示星环与任务星星",
    "panel_pin": "固定面板（保持展开）", "panel_unpin": "取消固定面板",
    "checking_wait": "每秒检查 · 等待数据", "settings_help": "设置与数据说明",
    "tray_tip": "petoken · 双击显示", "show_hide": "显示 / 隐藏",
    "show_hide_pet": "显示 / 隐藏桌宠", "move_right": "移回屏幕右侧",
    "exit_petoken": "退出 petoken", "settings_save_failed": "设置暂时无法保存",
    "mode_follow": "● 自动跟随", "mode_fixed": "◇ 已固定任务", "mode_working": "● 工作会话",
    "mode_recent": "◌ 最近活动 · 未识别前台", "waiting_data": "等待数据",
    "task_detection_tip": "Codex 通过窗口的辅助功能标题、Claude Code 通过会话登记识别当前任务。无法识别时明确退回最近活动；可在设置中固定。",
    "waiting_available_task": "等待可用任务", "active_session": "活动会话", "unnamed_task": "未命名任务",
    "model_not_recorded": "尚未记录模型",
    "model_tip": "最近一次已发送的模型配置。发送前的模型菜单改动可能尚未写入记录。",
    "effort_tip": "Reasoning effort · 最近一次已发送的配置",
    "no_reliable_record": "N/A · 没有可靠记录", "cached_input_line": "缓存输入：{value}",
    "output_includes_reasoning": "已包含 reasoning output，不重复相加。",
    "context_tip": "当前任务 · {used} / {window} Token\n最近一次记录的上下文占用，非累计 Token；与 CLI 的保留空间算法可能略有不同。",
    "cache_hit_new_work": "缓存命中 {ratio}  ·  新工作 {work}",
    "local_conversations": "{scope} · {count} 个本地会话",
    "known_price_usd": "已知单价部分 USD ${usd}",
    "not_subscription_bill": "不是订阅账单；按已记录的模型和服务档位折算，不含工具费用。",
    "unpriced_models": "尚无单价：{models}（可在设置中填写）",
    "partial_records": "部分记录缺失 / 重置，或排除了继承历史的 fork。",
    "quota_unavailable": "当前账户未提供此额度。", "unknown": "未知",
    "account_quota": "账户额度 · 剩余比例", "reset_time": "重置时间：{reset}",
    "quota_stale": "上次记录，等待刷新", "quota_live": "官方接口 · 每秒查询",
    "left": "剩余", "stale": "旧", "awaiting_reset": "等待服务端确认重置",
    "reset_in": "{duration} 后重置", "quota_waiting": "额度等待刷新", "quota_not_provided": "此来源不提供额度",
    "compat_partial": "部分兼容", "compat_unsupported": "格式无法识别",
    "compat_partial_tip": "Codex 本地数据有部分结构未能识别：相关数字显示 N/A，其余照常。",
    "compat_unsupported_tip": "Codex 本地数据格式无法识别（可能是 Codex 更新了），用量暂不可用。",
    "compat_version": "Codex 版本：{version}",
    "syncing": "每秒同步 · {time}", "token_last_written": "Token 最近写入：{seconds} 秒前",
    "no_token_events": "尚无 Token 事件", "no_model_usage": "读取不会调用模型或消耗模型 Token。",
    "quota_error": "额度暂不可用；保留上次读数，稍后重试。",
    "manual": "手动", "custom": "自定义",
    "pet_title": "petoken · 丝柯克桌宠",
    "pet_accessible": "丝柯克桌宠。点击展开用量，拖动移动，右键打开菜单。",
    "project_unavailable": "项目不可用", "codex_working": "Codex 工作中", "claude_working": "Claude Code 工作中",
    "pet_tooltip_tokens": "总计 {total} · 输入 {input} · 输出 {output}",
    "pet_tooltip_actions": "点击展开用量 · 拖动移动 · 右键菜单",
    "working": "工作中", "idle": "空闲", "context_short": "Ctx",
    "pet_toggle_panel": "打开 / 收起用量面板", "pet_settings": "设置与任务选择",
    "idle_motion": "待机动作", "hide_pet": "隐藏桌宠（托盘可恢复）", "exit": "退出",
    "analytics_title": "petoken · Token Analytics", "analytics_heading": "TOKEN ANALYTICS · {scope}",
    "tab_full": "完整用量", "tab_models": "按模型", "tab_conversations": "按会话",
    "tab_history": "日期与历史", "tab_raw": "原始字段 / 来源",
    "header_group_metric": "分组 / 指标", "header_exact": "精确值", "header_type_coverage": "类型 / 覆盖范围",
    "header_model": "模型", "header_conversation": "会话", "header_range": "范围",
    "header_date_local": "日期 / 本地时区", "records": "记录",
    "fx_rate_label": "1 USD = CAD",
    "header_input_tokens": "Input Tokens", "header_cached_tokens": "Cached Tokens",
    "header_uncached_tokens": "Uncached Tokens", "header_write_tokens": "Write Tokens",
    "header_output_tokens": "Output Tokens", "header_reasoning_tokens": "Reasoning Tokens",
    "header_nonreasoning_tokens": "Non-reasoning Tokens", "header_total_tokens": "Total Tokens",
    "analytics_subtitle": "{title} · {project} · {events:,} 条记录\n模型、会话、日期与历史均使用当前统计范围；全局仅代表本地可读取记录。",
    "history_initial": "本地索引历史 · 按系统本地时区；包括已归档会话。不是服务器账户的完整 lifetime。",
    "history_loaded": "本地索引历史 · 本地时区 / 日历天 · 不包括已删除、云端独有或未同步的记录。",
    "history_partial": " 存在缺失或已排除的继承历史，请视为部分记录。",
    "history_loading": "正在增量读取本地历史…",
    "analytics_na_note": "N/A = 缺少可靠数据。鼠标悬停查看公式与精确来源；部分已知小计会单独标注。",
    "analytics_default_note": "缓存输入与 reasoning 均为子项，不会再次计入 Total。",
    "raw": "原始", "derived": "派生", "known_subtotal": "已知小计 {value}",
    "total_source_coverage": "来源 total；缺失时仅以 input + output 回退",
    "range_current": "当前会话", "range_lifetime": "本地记录 lifetime", "range_today": "今天",
    "range_last7": "最近 7 个日历日", "range_last30": "最近 30 个日历日", "range_undated": "无日期 / 未分配",
    "group_official": "Official OpenAI", "group_cache": "Cache", "group_derived": "Derived", "group_comparison": "Comparison",
    "metric_total": "Total Tokens", "metric_input": "Input Tokens", "metric_cached": "Cached Input / Cache Read",
    "metric_uncached": "Uncached Input", "metric_output": "Output Tokens", "metric_reasoning": "Reasoning Tokens",
    "metric_nonreasoning": "Non-reasoning Output", "metric_cache_write": "Cache Write", "metric_cache_hit": "Cache Hit Ratio",
    "metric_new_work": "新工作 / 非缓存工作", "metric_output_ratio": "输出占比", "metric_reasoning_ratio": "Reasoning 输出占比",
    "metric_comparison_uncached": "不含 cache read 与 write 的输入", "metric_cache_read_component": "Cache Read 分量",
    "metric_cache_write_component": "Cache Write 分量", "metric_output_component": "输出分量",
    "metric_claude_raw": "Claude-style Raw Processed", "metric_known_processed": "可支持的 processed 小计",
    "unknown_model": "未知 / 未记录", "unknown_breakdown": "未知 / 缺少 Token 明细",
    "raw_field_notes": "未识别的额外源字段会保留在此处，但不会被解释或计入总数。",
    "help_total_tokens": "优先使用 OpenAI 官方 total；缺失时采用 input + output。缓存输入已包含在 input 中，reasoning 已包含在 output 中。",
    "help_total_tokens_claude": "Claude Code：总量 = 输入 + 输出。输入已包含缓存读取和缓存写入，思考 token 已包含在输出中。",
    "help_input_tokens": "来源 input_tokens，包含缓存输入及来源报告的 cache-write 输入。",
    "help_cached_input_tokens": "从缓存复用的已处理输入，是 input_tokens 的子项。",
    "help_uncached_input_tokens": "max(input − cached, 0)。未由缓存提供的输入；若报告 cache write，也包含在内。",
    "help_cache_write_input_tokens": "仅使用来源 cache_write_input_tokens / cache_write_tokens。缺失显示 N/A，不替换为 0；来源报告 0 时显示 0。",
    "help_output_tokens": "来源 output_tokens，已包含 reasoning 输出。",
    "help_reasoning_output_tokens": "来源报告的 reasoning Token，是输出用量的子项，不会再次加入总数。",
    "help_non_reasoning_output_tokens": "max(output − reasoning, 0)。",
    "help_new_work": "未缓存输入 + 输出，用于区分新处理的输入与重复缓存上下文。",
    "help_cache_hit_ratio": "cached ÷ input × 100。input 为 0 或必要字段缺失时显示 N/A。",
    "help_output_ratio": "output ÷ 官方 total × 100。total 为 0 时显示 N/A。",
    "help_reasoning_ratio": "reasoning ÷ output × 100。output 为 0 或 reasoning 缺失时显示 N/A。",
    "help_comparison_uncached": "对比分量：input − cache read − cache write。此处扣除 write，使四个对比分量互不重叠。",
    "help_claude_raw": "仅用于比较，不是 OpenAI 官方总数。非缓存/非 write 输入 + cache read + cache write + output。OpenAI 与 Claude 的缓存口径不同，不应直接比较 headline 总数；任一分量缺失时显示 N/A。",
    "help_known_processed": "可支持的小计：未缓存输入 + cache read + output。不会虚构 cache-write 明细或加入未知 write。",
    "status_no_local_data": "未找到 Codex 本地数据，请先在客户端打开一个任务。",
    "status_database_unavailable": "Codex 数据库暂时不可读，下一秒重试。",
    "status_pinned_unavailable": "固定的任务已不可用，请重新选择。",
    "status_no_desktop_task": "还没有本地桌面任务。", "status_project_unavailable": "当前会话没有可靠的项目身份。",
    "status_no_usage": "还没有本地用量记录。", "status_read_failed": "读取暂时失败，下一秒重试。",
    "display_all_usage": "全部用量", "display_local_history": "本地记录历史", "display_untitled": "未命名会话",
    "note_reset_missing_last": "计数器重置但缺少 last-request 记录；无法取得增量。",
    "note_reset_used_last": "累计计数器已重置：采用明确的 last-request 用量，不计重置快照。",
    "note_reset_carry": "重置快照含无法追踪的继承量；为避免重复未计入。",
    "note_initial_carry": "首个快照含更早且无时间/模型的用量；已作为未归属继承量保留。",
    "note_cache_write_unavailable": "Cache-write 明细不可用；费用未包含未知的 write 溢价。",
    "tracking_provider": "跟踪提供方", "tracking_auto": "自动", "tracking_codex": "Codex",
    "tracking_opencode": "OpenCode", "status_stale": "已过期",
    "tracking_claude": "Claude Code",
    "status_claude_no_local_data": "未找到 Claude Code 本地数据，请先在 Claude Code 中打开一个会话。",
    "analytics_provider_pending": "当前提供方为 OpenCode，分析视图将在后续更新中支持。",
    "analytics_heading_provider": "TOKEN ANALYTICS · {provider} · {scope}",
    "analytics_subtitle_opencode": "{title} · {project} · {count} 个本地会话 · {freshness}",
    "group_opencode_raw": "OpenCode 原始",
    "metric_recorded_cost": "已记录费用",
    "coverage_complete": "完整", "coverage_partial": "部分",
    "coverage_unknown": "未知", "coverage_unavailable": "不可用",
    "cost_recorded": "已记录 {amount} · 币种未知",
    "history_cached_as_of": "缓存快照 · 更新于 {time}",
    "history_refresh_pending": "有更新待刷新 —— 显示稳定快照",
    "history_skipped_rows": "已跳过 {count} 条异常记录 —— 部分统计",
    "history_unavailable": "此范围暂无日期历史",
    "analytics_opencode_note": "N/A = 没有验证口径。OpenCode 显示原始分类，对已验证版本另有记录 Total（非账单、非上下文）；费用为已记录金额，币种未知。",
    "raw_source_opencode": "OpenCode SQLite 会话汇总 + 消息元数据（不含内容）",
    "help_provider_analytics": "分析视图只描述当前来源与范围；切换范围会立即清空旧数据。",
    "help_recorded_cost": "会话汇总中已记录的金额之和；缺失会话不计入，币种未知。",
    "help_unknown_currency": "来源没有币种字段；金额不换算、不标注币种符号。",
    "help_opencode_total": "已验证版本且五个分类完整时，Total 为五个原始分类之和（记录 Total，非账单、非上下文）；缺失、部分或未验证版本时为 N/A。",
    "help_partial_coverage": "部分会话缺失该分类，只显示已知小计并标注部分。",
    "help_cached_history": "日期历史来自消息元数据聚合；缓存快照标明 as_of，待刷新时保持显示稳定快照。",
    "opencode_cost_tip": "已记录 {amount} · 币种未知，显示为 N/A",
    "opencode_model_tip": "提供方 {provider} · 变体 {variant} · 智能体 {agent}",
    "total_unavailable_note": "OpenCode 记录 Total：已验证版本下五个原始分类之和；不是账单金额，也不是当前上下文大小，不可用时为 N/A",
    "provider_mode_auto": "提供方：自动",
    "provider_mode_manual": "提供方：手动 · {provider}",
    "task_panel_label": "活动任务 {n}",
    "task_panel_total": "总计",
    "task_panel_input": "输入",
    "task_panel_output": "输出",
    "task_panel_reasoning": "推理",
    "task_panel_cache_read": "缓存读取",
    "task_panel_cache_write": "缓存写入",
    "task_panel_model": "模型",
    "task_panel_cost": "已记录费用",
    "task_panel_effort": "推理强度",
    "task_panel_variant": "模型变体",
    "task_panel_context": "上下文",
    "task_collapse": "收起任务详情",
    "task_accessible": "{label} · {provider} · 按 Enter 查看详情",
    "usage_panel": "用量面板",
    "panel_pinned_help": "用量面板已保持打开并置顶；在人物右键菜单取消勾选即可关闭。",
    "close_unpins_hub": "关闭用量面板（同时取消保持打开）",
    "task_overview": "活动任务 · {count}",
    "task_metric_scope": "用量：{provider} · {scope}",
    "task_source_unavailable": "用量来源不可用；已知记录可能不完整。",
    "task_usage_unavailable": "暂无已验证用量。",
    "task_record_note": "记录存在限制；仅显示已知用量。",
    "reset_task_layout": "重置任务布局",
}

EN = {
    "settings_title": "petoken · Settings", "save": "Save", "cancel": "Cancel",
    "language": "Display language", "language_zh_CN": "简体中文", "language_en": "English",
    "task_auto": "Automatically follow the current task", "task_unnamed": "Untitled task",
    "task_selection": "Follow / pinned task", "token_scope": "Token and cost scope",
    "reset_defaults": "Reset to Defaults", "confirm_reset": "Click again to confirm reset",
    "token_number_format": "Token number format", "token_format_full": "Full",
    "token_format_compact": "Compact", "manual_fx": "Manual exchange rate (clear to use Bank of Canada)",
    "custom_price": "Override Standard pricing for the current model", "model_unrecorded": "Model not recorded",
    "price_input": "Regular input", "price_cached": "Cached input", "price_write": "Cache write",
    "price_output": "Output (including reasoning)",
    "about_data": "About the Data",
    "about_1_title": "Cost Estimate",
    "about_1_body": "The displayed cost is an API-equivalent estimate and does not represent your actual ChatGPT, Codex or Claude subscription charge.",
    "about_2_title": "Token Usage",
    "about_2_body": "Usage is calculated from readable local Codex and Claude Code records. Cache and context values are derived from available data; missing records may result in partial totals, and tool-call costs are not included.",
    "about_3_title": "Model & Reasoning",
    "about_3_body": "Model and reasoning values usually follow the first configuration recorded for the session. Launcher-side or mid-session changes may not always be fully captured.",
    "about_4_title": "Status & Privacy",
    "about_4_body": "Status priority: Codex / Claude Code Working ＞ Microphone ＞ Music ＞ Typing ＞ Idle. The panel opens beside the desktop pet. Petoken never stores keystroke content or persistently saves media subtitle text.",
    "settings_save_error": "Could not save settings. Check write permission for your user folder.",
    "scope_global": "Global", "scope_global_recorded": "Global (Locally Recorded)",
    "scope_project": "Project", "scope_conversation": "Conversation",
    "spirit_accessible": "Ice spirit", "connecting": "Connecting…",
    "collapse_expand": "Collapse / expand", "hide_to_tray": "Hide to system tray",
    "waiting_codex": "Waiting for a task", "open_codex_task": "Open a task in Codex",
    "total_tokens": "TOTAL TOKENS", "input": "INPUT", "output": "OUTPUT",
    "switch_scope": "Switch usage scope", "analytics_button": "Token Analytics  ↗",
    "analytics_button_tip": "Open raw usage, derived metrics, models, conversations, and history",
    "context_used": "Context used", "five_hour_limit": "5-hour limit",
    "weekly_limit": "Weekly limit", "estimated_cost": "Estimated Cost",
    "currency": "Currency", "fx_unavailable_usd": "Exchange rate unavailable; showing USD.",
    "one_usd_equals": "1 USD = {rate} {currency}",
    "partial_estimate": "Partial Estimate", "always_on_top": "Always on Top",
    "character_size": "Character Size",
    "star_ring_enabled": "Show star ring and task Stars",
    "panel_pin": "Pin panel open", "panel_unpin": "Unpin panel",
    "checking_wait": "Checking every second · Waiting for data", "settings_help": "Settings and data notes",
    "tray_tip": "petoken · Double-click to show", "show_hide": "Show / hide",
    "show_hide_pet": "Show / hide desktop pet", "move_right": "Move to right side of screen",
    "exit_petoken": "Exit petoken", "settings_save_failed": "Settings could not be saved",
    "mode_follow": "● Following automatically", "mode_fixed": "◇ Pinned task", "mode_working": "● Working conversation",
    "mode_recent": "◌ Recently active · Foreground unknown", "waiting_data": "Waiting for data",
    "task_detection_tip": "The current task is identified from the Codex window accessibility title, or from the Claude Code session registry. If unavailable, the app explicitly falls back to recent activity; a task can also be pinned in Settings.",
    "waiting_available_task": "Waiting for an available task", "active_session": "Active session", "unnamed_task": "Untitled task",
    "model_not_recorded": "Model not recorded",
    "model_tip": "The most recently submitted model configuration. Menu changes may not be recorded until a message is sent.",
    "effort_tip": "Reasoning effort · Most recently submitted configuration",
    "no_reliable_record": "N/A · No reliable record", "cached_input_line": "Cached input: {value}",
    "output_includes_reasoning": "Reasoning output is already included and is not added again.",
    "context_tip": "Current task · {used} / {window} Tokens\nLatest recorded context use, not cumulative Tokens; it may differ slightly from the CLI reserved-space calculation.",
    "cache_hit_new_work": "Cache hit {ratio}  ·  New work {work}",
    "local_conversations": "{scope} · {count} local conversations",
    "known_price_usd": "Known-price portion USD ${usd}",
    "not_subscription_bill": "This is not a subscription bill. It converts recorded model and service-tier usage and excludes tool fees.",
    "unpriced_models": "No price for: {models} (add one in Settings)",
    "partial_records": "Some records are missing or reset, or inherited fork history was excluded.",
    "quota_unavailable": "This limit is unavailable for the current account.", "unknown": "Unknown",
    "account_quota": "Account limit · Remaining percentage", "reset_time": "Reset time: {reset}",
    "quota_stale": "Last recorded value; waiting to refresh", "quota_live": "Official endpoint · Queried every second",
    "left": "left", "stale": "stale", "awaiting_reset": "Waiting for the server to confirm reset",
    "reset_in": "Reset in {duration}", "quota_waiting": "Waiting for limit refresh", "quota_not_provided": "No limits from this source",
    "compat_partial": "Partly compatible", "compat_unsupported": "Format not recognized",
    "compat_partial_tip": "Some Codex local data structures were not recognized: those numbers show N/A, the rest is unaffected.",
    "compat_unsupported_tip": "The Codex local data format is not recognized (likely a Codex update); usage is unavailable for now.",
    "compat_version": "Codex version: {version}",
    "syncing": "Syncing every second · {time}", "token_last_written": "Token last written {seconds} seconds ago",
    "no_token_events": "No Token events yet", "no_model_usage": "Reading local data does not call a model or consume model Tokens.",
    "quota_error": "Limits are temporarily unavailable; keeping the last value and retrying later.",
    "manual": "Manual", "custom": "Custom",
    "pet_title": "petoken · Skirk Desktop Pet",
    "pet_accessible": "Skirk desktop pet. Click to view usage, drag to move, or right-click for the menu.",
    "project_unavailable": "Project unavailable", "codex_working": "Codex Working", "claude_working": "Claude Code Working",
    "pet_tooltip_tokens": "Total {total} · Input {input} · Output {output}",
    "pet_tooltip_actions": "Click to view usage · Drag to move · Right-click for menu",
    "working": "Working", "idle": "Idle", "context_short": "Ctx",
    "pet_toggle_panel": "Open / collapse usage panel", "pet_settings": "Settings and task selection",
    "idle_motion": "Idle motion", "hide_pet": "Hide desktop pet (restore from tray)", "exit": "Exit",
    "analytics_title": "petoken · Token Analytics", "analytics_heading": "TOKEN ANALYTICS · {scope}",
    "tab_full": "Full Usage", "tab_models": "By Model", "tab_conversations": "By Conversation",
    "tab_history": "Date && History", "tab_raw": "Raw Fields / Source",
    "header_group_metric": "Group / Metric", "header_exact": "Exact Value", "header_type_coverage": "Type / Coverage",
    "header_model": "Model", "header_conversation": "Conversation", "header_range": "Range",
    "header_date_local": "Date / Local Time", "records": "Records",
    "fx_rate_label": "1 USD = CAD",
    "header_input_tokens": "Input Tokens", "header_cached_tokens": "Cached Tokens",
    "header_uncached_tokens": "Uncached Tokens", "header_write_tokens": "Write Tokens",
    "header_output_tokens": "Output Tokens", "header_reasoning_tokens": "Reasoning Tokens",
    "header_nonreasoning_tokens": "Non-reasoning Tokens", "header_total_tokens": "Total Tokens",
    "analytics_subtitle": "{title} · {project} · {events:,} Records\nModels, conversations, dates, and history use the current scope. Global represents locally readable records only.",
    "history_initial": "Local indexed history · System local time; includes archived conversations. This is not complete server-account lifetime usage.",
    "history_loaded": "Local indexed history · Local time / calendar days · Excludes deleted, cloud-only, or unsynced records.",
    "history_partial": " Missing or excluded inherited history makes this a partial record.",
    "history_loading": "Reading local history incrementally…",
    "analytics_na_note": "N/A = reliable data is unavailable. Hover for formulas and exact sources; supported subtotals are shown separately.",
    "analytics_default_note": "Cached input and reasoning are subsets and are not added to Total again.",
    "raw": "raw", "derived": "derived", "known_subtotal": "known subtotal {value}",
    "total_source_coverage": "source total; falls back only to input + output when missing",
    "range_current": "Current session", "range_lifetime": "Local recorded lifetime", "range_today": "Today",
    "range_last7": "Last 7 calendar days", "range_last30": "Last 30 calendar days", "range_undated": "Undated / unallocated",
    "group_official": "Official OpenAI Usage", "group_cache": "Cache", "group_derived": "Derived Analytics", "group_comparison": "Comparison",
    "metric_total": "Total Tokens", "metric_input": "Input Tokens", "metric_cached": "Cached Input / Cache Read",
    "metric_uncached": "Uncached Input", "metric_output": "Output Tokens", "metric_reasoning": "Reasoning Tokens",
    "metric_nonreasoning": "Non-reasoning Output", "metric_cache_write": "Cache Write", "metric_cache_hit": "Cache Hit Ratio",
    "metric_new_work": "New / Non-cached Work", "metric_output_ratio": "Output Ratio", "metric_reasoning_ratio": "Reasoning Share of Output",
    "metric_comparison_uncached": "Input excluding cache read AND write", "metric_cache_read_component": "Cache Read component",
    "metric_cache_write_component": "Cache Write component", "metric_output_component": "Output component",
    "metric_claude_raw": "Claude-style Raw Processed", "metric_known_processed": "Supported processed subtotal",
    "unknown_model": "Unknown / Not recorded", "unknown_breakdown": "Unknown / missing Token breakdown",
    "raw_field_notes": "Unknown extra source fields are preserved here but are not interpreted or added to totals.",
    "help_total_tokens": "Official OpenAI total where available; otherwise input + output. Cached input is already inside input, and reasoning is already inside output.",
    "help_total_tokens_claude": "Claude Code: total = input + output. Input already includes cache reads and writes; thinking tokens are already inside output.",
    "help_input_tokens": "Source input_tokens. Includes cached input and any reported cache-write input.",
    "help_cached_input_tokens": "Previously processed input reused from cache; a subset of input_tokens.",
    "help_uncached_input_tokens": "max(input − cached, 0). Input not served from cache; includes cache writes if reported.",
    "help_cache_write_input_tokens": "Source cache_write_input_tokens / cache_write_tokens only. Missing = N/A, not zero. A reported 0 is displayed as 0.",
    "help_output_tokens": "Source output_tokens. Already includes reasoning output.",
    "help_reasoning_output_tokens": "Reasoning Tokens reported as part of output usage; not added again to total.",
    "help_non_reasoning_output_tokens": "max(output − reasoning, 0).",
    "help_new_work": "Uncached input + output. Useful for separating newly processed work from repeated cached context.",
    "help_cache_hit_ratio": "cached ÷ input × 100. N/A if input is zero or a required field is missing.",
    "help_output_ratio": "output ÷ official total × 100. N/A if total is zero.",
    "help_reasoning_ratio": "reasoning ÷ output × 100. N/A if output is zero or reasoning is missing.",
    "help_comparison_uncached": "Comparison component: input − cache read − cache write. Writes are removed so the four components do not overlap.",
    "help_claude_raw": "Comparison only, not the official total. Non-cache/non-write input + cache read + cache write + output. OpenAI and Claude expose caching differently, so their headline totals should not be compared blindly. N/A when a component is unavailable.",
    "help_known_processed": "Supported subtotal: uncached input + cache read + output. Does not invent a cache-write split or add unknown writes.",
    "status_no_local_data": "No local Codex data found. Open a task in the client first.",
    "status_database_unavailable": "The Codex database is temporarily unreadable. Retrying next second.",
    "status_pinned_unavailable": "The pinned task is unavailable. Select it again.",
    "status_no_desktop_task": "No local desktop task is available yet.", "status_project_unavailable": "The current conversation has no reliable project identity.",
    "status_no_usage": "No local usage records are available yet.", "status_read_failed": "Reading temporarily failed. Retrying next second.",
    "display_all_usage": "All usage", "display_local_history": "Locally recorded history", "display_untitled": "Untitled conversation",
    "note_reset_missing_last": "Counter reset without a last-request record; the increment is unavailable.",
    "note_reset_used_last": "Cumulative counter reset: counted explicit last-request usage instead of the reset snapshot.",
    "note_reset_carry": "The reset snapshot contains untraceable carry; it was not added to avoid duplication.",
    "note_initial_carry": "The first snapshot contains earlier usage without timestamps or model; retained as unattributed carry.",
    "note_cache_write_unavailable": "Cache-write split is unavailable; cost excludes any unknown write premium.",
    "tracking_provider": "Tracking provider", "tracking_auto": "Auto", "tracking_codex": "Codex",
    "tracking_opencode": "OpenCode", "status_stale": "Stale",
    "tracking_claude": "Claude Code",
    "status_claude_no_local_data": "No local Claude Code data found. Start a session in Claude Code first.",
    "analytics_provider_pending": "The current provider is OpenCode; analytics support arrives in a later update.",
    "analytics_heading_provider": "TOKEN ANALYTICS · {provider} · {scope}",
    "analytics_subtitle_opencode": "{title} · {project} · {count} local sessions · {freshness}",
    "group_opencode_raw": "OpenCode raw",
    "metric_recorded_cost": "Recorded Cost",
    "coverage_complete": "complete", "coverage_partial": "partial",
    "coverage_unknown": "unknown", "coverage_unavailable": "unavailable",
    "cost_recorded": "Recorded {amount} · currency unavailable",
    "history_cached_as_of": "Cached snapshot · as of {time}",
    "history_refresh_pending": "Refresh pending — showing the stable snapshot",
    "history_skipped_rows": "{count} malformed rows skipped — partial",
    "history_unavailable": "No daily history for this scope",
    "analytics_opencode_note": "N/A = no verified meaning. OpenCode shows raw categories plus a recorded Total for verified versions (not billing, not context); cost is a recorded amount with unknown currency.",
    "raw_source_opencode": "OpenCode SQLite session rollups + message metadata (no content)",
    "help_provider_analytics": "Analytics describes the current provider and scope; changing scope clears stale data at once.",
    "help_recorded_cost": "Sum of recorded session amounts; sessions without amounts are excluded; currency unknown.",
    "help_unknown_currency": "The source has no currency field; amounts are never converted or labelled with a symbol.",
    "help_opencode_total": "Total is the five-category sum only for verified versions with complete data (a recorded total, not billing or context); missing, partial, or unverified versions stay N/A.",
    "help_partial_coverage": "Some sessions lack this category; only the known subtotal is shown and marked partial.",
    "help_cached_history": "Daily history aggregates message metadata; cached snapshots carry as_of and stay stable while pending.",
    "opencode_cost_tip": "Recorded {amount} · currency unstated, shown as N/A",
    "opencode_model_tip": "Provider {provider} · variant {variant} · agent {agent}",
    "total_unavailable_note": "OpenCode recorded Total: the five-category sum for verified versions; not a billed amount or current context size, N/A when unavailable",
    "provider_mode_auto": "Provider: Auto",
    "provider_mode_manual": "Provider: Manual · {provider}",
    "task_panel_label": "Active task {n}",
    "task_panel_total": "Total",
    "task_panel_input": "Input",
    "task_panel_output": "Output",
    "task_panel_reasoning": "Reasoning",
    "task_panel_cache_read": "Cache Read",
    "task_panel_cache_write": "Cache Write",
    "task_panel_model": "Model",
    "task_panel_cost": "Recorded cost",
    "task_panel_effort": "Reasoning effort",
    "task_panel_variant": "Model variant",
    "task_panel_context": "Context",
    "task_collapse": "Collapse task details",
    "task_accessible": "{label} · {provider} · Press Enter for details",
    "usage_panel": "Usage panel",
    "panel_pinned_help": "The usage panel stays open and on top. Uncheck it in the pet's context menu to close it.",
    "close_unpins_hub": "Close the usage panel (also stops keeping it open)",
    "task_overview": "Active tasks · {count}",
    "task_metric_scope": "Usage: {provider} · {scope}",
    "task_source_unavailable": "Usage source unavailable; known records may be incomplete.",
    "task_usage_unavailable": "No verified usage available.",
    "task_record_note": "Records have limitations; only known usage is shown.",
    "reset_task_layout": "Reset task layout",
}

ZH_CN.update({
    'workbench_open': '打开工作台',
    'wb_heading': '你的小天地', 'wb_subtitle': '记下生活的小事，也留好工作里的下一步。',
    'wb_spaces': '项目空间', 'wb_local': '保存在此设备',
    'wb_all': '全部项目', 'wb_inbox': '未分类',
    'wb_home': '首页', 'wb_todos': '待办', 'wb_notes': '便签', 'wb_projects': '项目',
    'wb_next': '接下来做什么', 'wb_codex_tasks': '当前任务',
    'wb_summary': '{projects} 个项目    ·    {todos} 项待办    ·    {notes} 张便签',
    'wb_empty_todos': '暂时没有待办，给下一步留个位置。',
    'wb_empty_tasks': '当前没有 Codex 或 Claude Code 任务。任务出现后会显示在这里。',
    'wb_empty_notes': '新建或选择一张便签，记下你的想法。',
    'wb_empty_projects': '还没有项目。创建一个空间，把相关事项放在一起。',
    'wb_details': '查看详情', 'wb_link': '关联项目',
    'wb_todo_intro': '勾选完成，也可以随时重新打开。',
    'wb_add': '添加', 'wb_completed': '显示已完成', 'wb_edit': '编辑', 'wb_delete': '删除',
    'wb_todo_placeholder': '下一件想做的事…',
    'wb_new_note': '新建便签', 'wb_save': '保存 · Ctrl+S',
    'wb_note_title': '便签标题', 'wb_note_body': '写点什么…', 'wb_untitled': '未命名便签',
    'wb_unsaved': '未保存 · 切换或关闭前会提醒你', 'wb_saved': '已保存到此设备',
    'wb_projects_intro': '每个项目有自己的待办和便签，也可以关联 Codex 或 Claude Code 任务。',
    'wb_new_project': '新建项目', 'wb_name': '名称', 'wb_project': '项目',
    'wb_folder': '文件夹（可选）', 'wb_folder_open': '打开文件夹', 'wb_browse': '选择',
    'wb_error': '操作未完成。请检查输入或稍后重试；尚未保存的内容已保留。',
    'wb_open_error': '无法打开工作台。数据文件可能被占用或格式不受支持；原文件未被替换。',
    'wb_folder_error': '无法打开文件夹，请检查项目中的路径。',
    'wb_save_confirm': '便签尚未保存，是否保存更改？',
    'wb_delete_confirm': '删除这项待办？此操作无法撤销。',
    'wb_delete_note_confirm': '删除这张便签及尚未保存的编辑？此操作无法撤销。',
    'wb_delete_project_confirm': '删除这个项目？待办和便签会保留在「未分类」中，关联的任务不会被删除。',
})
EN.update({
    'workbench_open': 'Open workbench',
    'wb_heading': 'Your little corner', 'wb_subtitle': 'Everyday notes and your next small step, together.',
    'wb_spaces': 'Project spaces', 'wb_local': 'Saved on this device',
    'wb_all': 'All projects', 'wb_inbox': 'Unassigned',
    'wb_home': 'Home', 'wb_todos': 'Todos', 'wb_notes': 'Notes', 'wb_projects': 'Projects',
    'wb_next': 'Up next', 'wb_codex_tasks': 'Current tasks',
    'wb_summary': '{projects} projects    ·    {todos} pending    ·    {notes} notes',
    'wb_empty_todos': 'Nothing pending. Make room for your next step.',
    'wb_empty_tasks': 'No current Codex or Claude Code tasks. They will appear here when available.',
    'wb_empty_notes': 'Create or select a note to capture an idea.',
    'wb_empty_projects': 'No projects yet. Create a space for related work.',
    'wb_details': 'View details', 'wb_link': 'Link project',
    'wb_todo_intro': 'Check off a finished task, or reopen it any time.',
    'wb_add': 'Add', 'wb_completed': 'Show completed', 'wb_edit': 'Edit', 'wb_delete': 'Delete',
    'wb_todo_placeholder': 'Your next step…',
    'wb_new_note': 'New note', 'wb_save': 'Save · Ctrl+S',
    'wb_note_title': 'Note title', 'wb_note_body': 'Write something…', 'wb_untitled': 'Untitled note',
    'wb_unsaved': 'Unsaved · you will be asked before leaving', 'wb_saved': 'Saved on this device',
    'wb_projects_intro': 'Keep todos and notes together, and link related Codex or Claude Code tasks.',
    'wb_new_project': 'New project', 'wb_name': 'Name', 'wb_project': 'Project',
    'wb_folder': 'Folder (optional)', 'wb_folder_open': 'Open folder', 'wb_browse': 'Browse',
    'wb_error': 'Could not complete the action. Check your input or try again; unsaved edits are retained.',
    'wb_open_error': 'Could not open the workbench. The file may be busy or unsupported; it has not been replaced.',
    'wb_folder_error': 'Could not open the folder. Check the project path.',
    'wb_save_confirm': 'This note has unsaved changes. Save them?',
    'wb_delete_confirm': 'Delete this todo? This cannot be undone.',
    'wb_delete_note_confirm': 'Delete this note and its unsaved edits? This cannot be undone.',
    'wb_delete_project_confirm': 'Delete this project? Todos and notes move to Unassigned. Linked tasks are kept.',
})

ZH_CN.update({
    'wb_tutorial': '新手教程', 'wb_tutorial_step': '第 {n} / 5 步',
    'wb_tutorial_skip': '跳过教程', 'wb_tutorial_back': '上一步',
    'wb_tutorial_next': '下一步', 'wb_tutorial_done': '完成教程',
    'wb_tutorial_hint': '点击操作会收起教程。工作台右上角的「新手教程」可以继续或重新查看。',
    'wb_tutorial_title_0': '和桌宠一起开始',
    'wb_tutorial_body_0': '拖动人物可以移动桌宠，右键人物或托盘图标可打开工作台、用量面板和设置。\n\n工作台用来整理项目、待办和便签。即使没有运行 Codex 或 Claude Code，也可以使用这些功能。\n\n先看看界面，或点击「下一步」跟着试一试。',
    'wb_tutorial_action_0': '先看看工作台',
    'wb_tutorial_title_1': '先给事情一个家',
    'wb_tutorial_body_1': '项目把相关的待办和便签放在一起，例如「学习」或「我的桌宠」。\n\n点击下面的按钮，填写项目名称。文件夹是可选的，方便以后打开资料。\n\n左侧选择一个项目，就能查看属于它的内容；「未分类」用来随手记录。',
    'wb_tutorial_action_1': '创建一个项目',
    'wb_tutorial_title_2': '写下下一件事',
    'wb_tutorial_body_2': '进入「待办」，输入一件想做的事，选择所属项目，然后点「添加」或按回车。\n\n做完后勾选它；需要继续时，取消勾选即可重新打开。\n\n「首页」会汇总当前项目中尚未完成的事项。',
    'wb_tutorial_action_2': '去添加待办',
    'wb_tutorial_title_3': '把想法留下来',
    'wb_tutorial_body_3': '新建便签，写一个标题和内容，点击「保存」或按 Ctrl+S。便签和待办保存在这台设备上。\n\n切换便签、项目或退出时，未保存的编辑会提示你选择保存、放弃或取消。\n\n现在试着写下一句话吧。',
    'wb_tutorial_action_3': '新建一张便签',
    'wb_tutorial_title_4': '让星星陪你工作',
    'wb_tutorial_body_4': '每颗星星对应一个当前任务：Codex 是蓝色，Claude Code 是金色。点击星星，或在首页选择任务后点「查看详情」，可以查看它的用量信息。\n\n「关联项目」可以把这个任务放进你自己的项目空间。\n\n没有任务时列表为空是正常的。使用 Codex 或 Claude Code 后，可用任务会自动出现；个人待办和便签照常使用。',
    'wb_tutorial_action_4': '看看当前任务',
})
EN.update({
    'wb_tutorial': 'Getting started', 'wb_tutorial_step': 'Step {n} of 5',
    'wb_tutorial_skip': 'Skip tutorial', 'wb_tutorial_back': 'Back',
    'wb_tutorial_next': 'Next', 'wb_tutorial_done': 'Finish',
    'wb_tutorial_hint': 'An action hides this guide. Use Getting started at the top right to resume or revisit it.',
    'wb_tutorial_title_0': 'A small place to start',
    'wb_tutorial_body_0': 'Drag the character to move your pet. Right-click the character or tray icon to open the workbench, usage panel or settings.\n\nUse the workbench for projects, todos and notes, even when Codex and Claude Code are not running.\n\nLook around, or choose Next to try the basics.',
    'wb_tutorial_action_0': 'Look around the workbench',
    'wb_tutorial_title_1': 'Give your work a home',
    'wb_tutorial_body_1': 'A project keeps related todos and notes together, such as Study or My desktop pet.\n\nChoose the button below and enter a name. A folder is optional and lets you open your materials later.\n\nSelect a project in the sidebar to filter its content. Unassigned is a place for quick captures.',
    'wb_tutorial_action_1': 'Create a project',
    'wb_tutorial_title_2': 'Write your next step',
    'wb_tutorial_body_2': 'In Todos, enter something you want to do, choose a project, then select Add or press Enter.\n\nCheck it off when done. Uncheck it to reopen it.\n\nHome collects the pending items for the selected project.',
    'wb_tutorial_action_2': 'Go to Todos',
    'wb_tutorial_title_3': 'Keep a small idea',
    'wb_tutorial_body_3': 'Create a note, write a title and some text, then select Save or press Ctrl+S. Notes and todos stay on this device.\n\nWhen you switch notes or projects, or exit, unsaved edits prompt you to Save, Discard or Cancel.\n\nTry writing one sentence.',
    'wb_tutorial_action_3': 'Create a note',
    'wb_tutorial_title_4': 'Work alongside the stars',
    'wb_tutorial_body_4': 'Each star represents a current task: blue for Codex, gold for Claude Code. Select a star, or choose a task on Home and View details, to see its available usage.\n\nLink project puts the task in your own project space.\n\nAn empty task list is normal when none are available. Codex and Claude Code tasks appear automatically; personal todos and notes still work.',
    'wb_tutorial_action_4': 'Look at current tasks',
})

STRINGS = {"zh_CN": ZH_CN, "en": EN}


def normalize_language(value):
    return value if value in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def text(key, language=DEFAULT_LANGUAGE, **values):
    language = normalize_language(language)
    template = STRINGS[language].get(key, STRINGS[DEFAULT_LANGUAGE].get(key, key))
    return template.format(**values) if values else template


def scope_text(scope, language=DEFAULT_LANGUAGE, recorded=False):
    if not isinstance(scope, str):
        scope = "conversation"
    scope = {"task": "conversation"}.get(scope, scope)
    key = "scope_global_recorded" if scope == "global" and recorded else f"scope_{scope}"
    return text(key if key in STRINGS[DEFAULT_LANGUAGE] else "scope_conversation", language)
