"""Central Simplified Chinese and English user-interface strings."""

DEFAULT_LANGUAGE = "zh_CN"
SUPPORTED_LANGUAGES = ("zh_CN", "en")

ZH_CN = {
    "settings_title": "petoken · 设置", "save": "保存", "cancel": "取消",
    "language": "界面语言", "language_zh_CN": "简体中文", "language_en": "English",
    "task_auto": "自动跟随 Codex 当前任务", "task_unnamed": "未命名任务",
    "task_selection": "跟随 / 固定任务", "token_scope": "Token 与费用范围",
    "reset_defaults": "恢复默认设置", "confirm_reset": "再次点击确认重置",
    "token_number_format": "Token 数字格式", "token_format_full": "完整数字",
    "token_format_compact": "紧凑格式", "manual_fx": "手动汇率（取消后使用加拿大央行）",
    "custom_price": "覆盖当前模型的 Standard 单价", "model_unrecorded": "模型尚未记录",
    "price_input": "普通输入", "price_cached": "缓存输入", "price_write": "缓存写入",
    "price_output": "输出（含 reasoning）",
    "about_data": "关于数据",
    "about_1_title": "费用估算",
    "about_1_body": "显示的是 API 等价费用估算，不代表 ChatGPT / Codex 订阅的实际扣费。",
    "about_2_title": "Token 统计",
    "about_2_body": "数据来自本地可读取的 Codex 记录。缓存、Context 等根据现有记录计算；缺失记录时，结果可能只是部分统计，且不包含工具调用费用。",
    "about_3_title": "模型与推理强度",
    "about_3_body": "模型和 reasoning 通常以会话首次记录的配置为准。通过启动器或会话中途修改的设置，不一定会被完整记录。",
    "about_4_title": "状态与隐私",
    "about_4_body": "状态优先级：Codex 工作 ＞ 麦克风 ＞ 音乐 ＞ 打字 ＞ 待机。浮窗会跟随桌宠展开。Petoken 不保存你输入的按键内容，也不会持久化保存媒体字幕内容。",
    "settings_save_error": "无法保存设置，请检查用户文件夹的写入权限。",
    "scope_global": "全局", "scope_global_recorded": "全局（本地记录）",
    "scope_project": "项目", "scope_conversation": "会话",
    "spirit_accessible": "冰晶小精灵", "connecting": "正在连接…",
    "collapse_expand": "收起 / 展开", "hide_to_tray": "隐藏到系统托盘",
    "waiting_codex": "等待 Codex", "open_codex_task": "打开 Codex 中的任务",
    "total_tokens": "TOTAL TOKENS", "input": "INPUT", "output": "OUTPUT",
    "switch_scope": "切换统计范围", "analytics_button": "Token Analytics  ↗",
    "analytics_button_tip": "展开完整原始用量、派生指标、模型、会话与历史",
    "context_used": "Context 已用", "five_hour_limit": "5 小时限额",
    "weekly_limit": "每周限额", "estimated_cost": "预估费用",
    "currency": "货币", "fx_unavailable_usd": "汇率暂不可用；以 USD 显示。",
    "one_usd_equals": "1 USD = {rate} {currency}",
    "partial_estimate": "部分估算", "always_on_top": "始终置顶",
    "character_size": "角色大小",
    "panel_pin": "固定面板（保持展开）", "panel_unpin": "取消固定面板",
    "checking_wait": "每秒检查 · 等待数据", "settings_help": "设置与数据说明",
    "tray_tip": "petoken · 双击显示", "show_hide": "显示 / 隐藏",
    "show_hide_pet": "显示 / 隐藏桌宠", "move_right": "移回屏幕右侧",
    "exit_petoken": "退出 petoken", "settings_save_failed": "设置暂时无法保存",
    "mode_follow": "● 自动跟随", "mode_fixed": "◇ 已固定任务", "mode_working": "● 工作会话",
    "mode_recent": "◌ 最近活动 · 未识别前台", "waiting_data": "等待数据",
    "task_detection_tip": "通过 Codex 窗口的辅助功能标题识别当前任务。无法识别时明确退回最近活动；可在设置中固定。",
    "waiting_available_task": "等待可用任务", "active_session": "活动会话", "unnamed_task": "未命名任务",
    "model_not_recorded": "尚未记录模型",
    "model_tip": "最近一次已发送的模型配置。发送前的模型菜单改动可能尚未写入记录。",
    "effort_tip": "Reasoning effort · 最近一次已发送的配置",
    "no_reliable_record": "N/A · 没有可靠记录", "cached_input_line": "缓存输入：{value}",
    "output_includes_reasoning": "已包含 reasoning output，不重复相加。",
    "context_tip": "当前任务 · {used} / {window} Token\n最近一次记录的上下文占用，非累计 Token；与 CLI 的保留空间算法可能略有不同。",
    "cache_hit_new_work": "缓存命中 {ratio}  ·  新工作 {work}",
    "local_conversations": "{scope} · {count} 个本地会话",
    "known_price_usd": "已知单价部分 USD ${usd}",
    "not_subscription_bill": "不是订阅账单；按已记录的模型和服务档位折算，不含工具费用。",
    "unpriced_models": "尚无单价：{models}（可在设置中填写）",
    "partial_records": "部分记录缺失 / 重置，或排除了继承历史的 fork。",
    "quota_unavailable": "当前账户未提供此额度。", "unknown": "未知",
    "account_quota": "账户额度 · 剩余比例", "reset_time": "重置时间：{reset}",
    "quota_stale": "上次记录，等待刷新", "quota_live": "官方接口 · 每秒查询",
    "left": "剩余", "stale": "旧", "awaiting_reset": "等待服务端确认重置",
    "reset_in": "{duration} 后重置", "quota_waiting": "额度等待刷新",
    "syncing": "每秒同步 · {time}", "token_last_written": "Token 最近写入：{seconds} 秒前",
    "no_token_events": "尚无 Token 事件", "no_model_usage": "读取不会调用模型或消耗模型 Token。",
    "quota_error": "额度暂不可用；保留上次读数，稍后重试。",
    "manual": "手动", "custom": "自定义",
    "pet_title": "petoken · 丝柯克桌宠",
    "pet_accessible": "丝柯克桌宠。点击展开用量，拖动移动，右键打开菜单。",
    "project_unavailable": "项目不可用", "codex_working": "Codex 工作中",
    "pet_tooltip_tokens": "总计 {total} · 输入 {input} · 输出 {output}",
    "pet_tooltip_actions": "点击展开用量 · 拖动移动 · 右键菜单",
    "working": "工作中", "idle": "空闲", "context_short": "Ctx",
    "pet_toggle_panel": "打开 / 收起用量面板", "pet_settings": "设置与任务选择",
    "idle_motion": "待机动作", "hide_pet": "隐藏桌宠（托盘可恢复）", "exit": "退出",
    "analytics_title": "petoken · Token Analytics", "analytics_heading": "TOKEN ANALYTICS · {scope}",
    "tab_full": "完整用量", "tab_models": "按模型", "tab_conversations": "按会话",
    "tab_history": "日期与历史", "tab_raw": "原始字段 / 来源",
    "header_group_metric": "分组 / 指标", "header_exact": "精确值", "header_type_coverage": "类型 / 覆盖范围",
    "header_model": "模型", "header_conversation": "会话", "header_range": "范围",
    "header_date_local": "日期 / 本地时区", "records": "记录",
    "fx_rate_label": "1 USD = CAD",
    "header_input_tokens": "Input Tokens", "header_cached_tokens": "Cached Tokens",
    "header_uncached_tokens": "Uncached Tokens", "header_write_tokens": "Write Tokens",
    "header_output_tokens": "Output Tokens", "header_reasoning_tokens": "Reasoning Tokens",
    "header_nonreasoning_tokens": "Non-reasoning Tokens", "header_total_tokens": "Total Tokens",
    "analytics_subtitle": "{title} · {project} · {events:,} 条记录\n模型、会话、日期与历史均使用当前统计范围；全局仅代表本地可读取记录。",
    "history_initial": "本地索引历史 · 按系统本地时区；包括已归档会话。不是服务器账户的完整 lifetime。",
    "history_loaded": "本地索引历史 · 本地时区 / 日历天 · 不包括已删除、云端独有或未同步的记录。",
    "history_partial": " 存在缺失或已排除的继承历史，请视为部分记录。",
    "history_loading": "正在增量读取本地历史…",
    "analytics_na_note": "N/A = 缺少可靠数据。鼠标悬停查看公式与精确来源；部分已知小计会单独标注。",
    "analytics_default_note": "缓存输入与 reasoning 均为子项，不会再次计入 Total。",
    "raw": "原始", "derived": "派生", "known_subtotal": "已知小计 {value}",
    "total_source_coverage": "来源 total；缺失时仅以 input + output 回退",
    "range_current": "当前会话", "range_lifetime": "本地记录 lifetime", "range_today": "今天",
    "range_last7": "最近 7 个日历日", "range_last30": "最近 30 个日历日", "range_undated": "无日期 / 未分配",
    "group_official": "Official OpenAI", "group_cache": "Cache", "group_derived": "Derived", "group_comparison": "Comparison",
    "metric_total": "Total Tokens", "metric_input": "Input Tokens", "metric_cached": "Cached Input / Cache Read",
    "metric_uncached": "Uncached Input", "metric_output": "Output Tokens", "metric_reasoning": "Reasoning Tokens",
    "metric_nonreasoning": "Non-reasoning Output", "metric_cache_write": "Cache Write", "metric_cache_hit": "Cache Hit Ratio",
    "metric_new_work": "新工作 / 非缓存工作", "metric_output_ratio": "输出占比", "metric_reasoning_ratio": "Reasoning 输出占比",
    "metric_comparison_uncached": "不含 cache read 与 write 的输入", "metric_cache_read_component": "Cache Read 分量",
    "metric_cache_write_component": "Cache Write 分量", "metric_output_component": "输出分量",
    "metric_claude_raw": "Claude-style Raw Processed", "metric_known_processed": "可支持的 processed 小计",
    "unknown_model": "未知 / 未记录", "unknown_breakdown": "未知 / 缺少 Token 明细",
    "raw_field_notes": "未识别的额外源字段会保留在此处，但不会被解释或计入总数。",
    "help_total_tokens": "优先使用 OpenAI 官方 total；缺失时采用 input + output。缓存输入已包含在 input 中，reasoning 已包含在 output 中。",
    "help_input_tokens": "来源 input_tokens，包含缓存输入及来源报告的 cache-write 输入。",
    "help_cached_input_tokens": "从缓存复用的已处理输入，是 input_tokens 的子项。",
    "help_uncached_input_tokens": "max(input − cached, 0)。未由缓存提供的输入；若报告 cache write，也包含在内。",
    "help_cache_write_input_tokens": "仅使用来源 cache_write_input_tokens / cache_write_tokens。缺失显示 N/A，不替换为 0；来源报告 0 时显示 0。",
    "help_output_tokens": "来源 output_tokens，已包含 reasoning 输出。",
    "help_reasoning_output_tokens": "来源报告的 reasoning Token，是输出用量的子项，不会再次加入总数。",
    "help_non_reasoning_output_tokens": "max(output − reasoning, 0)。",
    "help_new_work": "未缓存输入 + 输出，用于区分新处理的输入与重复缓存上下文。",
    "help_cache_hit_ratio": "cached ÷ input × 100。input 为 0 或必要字段缺失时显示 N/A。",
    "help_output_ratio": "output ÷ 官方 total × 100。total 为 0 时显示 N/A。",
    "help_reasoning_ratio": "reasoning ÷ output × 100。output 为 0 或 reasoning 缺失时显示 N/A。",
    "help_comparison_uncached": "对比分量：input − cache read − cache write。此处扣除 write，使四个对比分量互不重叠。",
    "help_claude_raw": "仅用于比较，不是 OpenAI 官方总数。非缓存/非 write 输入 + cache read + cache write + output。OpenAI 与 Claude 的缓存口径不同，不应直接比较 headline 总数；任一分量缺失时显示 N/A。",
    "help_known_processed": "可支持的小计：未缓存输入 + cache read + output。不会虚构 cache-write 明细或加入未知 write。",
    "status_no_local_data": "未找到 Codex 本地数据，请先在客户端打开一个任务。",
    "status_database_unavailable": "Codex 数据库暂时不可读，下一秒重试。",
    "status_pinned_unavailable": "固定的任务已不可用，请重新选择。",
    "status_no_desktop_task": "还没有本地桌面任务。", "status_project_unavailable": "当前会话没有可靠的项目身份。",
    "status_no_usage": "还没有本地用量记录。", "status_read_failed": "读取暂时失败，下一秒重试。",
    "display_all_usage": "全部 Codex 用量", "display_local_history": "本地记录历史", "display_untitled": "未命名会话",
    "note_reset_missing_last": "计数器重置但缺少 last-request 记录；无法取得增量。",
    "note_reset_used_last": "累计计数器已重置：采用明确的 last-request 用量，不计重置快照。",
    "note_reset_carry": "重置快照含无法追踪的继承量；为避免重复未计入。",
    "note_initial_carry": "首个快照含更早且无时间/模型的用量；已作为未归属继承量保留。",
    "note_cache_write_unavailable": "Cache-write 明细不可用；费用未包含未知的 write 溢价。",
    "tracking_provider": "跟踪提供方", "tracking_auto": "自动", "tracking_codex": "Codex",
    "tracking_opencode": "OpenCode", "status_stale": "已过期",
    "analytics_provider_pending": "当前提供方为 OpenCode，分析视图将在后续更新中支持。",
    "analytics_heading_provider": "TOKEN ANALYTICS · {provider} · {scope}",
    "analytics_subtitle_opencode": "{title} · {project} · {count} 个本地会话 · {freshness}",
    "group_opencode_raw": "OpenCode 原始",
    "metric_recorded_cost": "已记录费用",
    "coverage_complete": "完整", "coverage_partial": "部分",
    "coverage_unknown": "未知", "coverage_unavailable": "不可用",
    "cost_recorded": "已记录 {amount} · 币种未知",
    "history_cached_as_of": "缓存快照 · 更新于 {time}",
    "history_refresh_pending": "有更新待刷新 —— 显示稳定快照",
    "history_skipped_rows": "已跳过 {count} 条异常记录 —— 部分统计",
    "history_unavailable": "此范围暂无日期历史",
    "analytics_opencode_note": "N/A = 没有验证口径。OpenCode 显示原始分类，对已验证版本另有记录 Total（非账单、非上下文）；费用为已记录金额，币种未知。",
    "raw_source_opencode": "OpenCode SQLite 会话汇总 + 消息元数据（不含内容）",
    "help_provider_analytics": "分析视图只描述当前提供方与当前范围；切换提供方或范围会立即清空旧数据。",
    "help_recorded_cost": "会话汇总中已记录的金额之和；缺失会话不计入，币种未知。",
    "help_unknown_currency": "来源没有币种字段；金额不换算、不标注币种符号。",
    "help_opencode_total": "已验证版本且五个分类完整时，Total 为五个原始分类之和（记录 Total，非账单、非上下文）；缺失、部分或未验证版本时为 N/A。",
    "help_partial_coverage": "部分会话缺失该分类，只显示已知小计并标注部分。",
    "help_cached_history": "日期历史来自消息元数据聚合；缓存快照标明 as_of，待刷新时保持显示稳定快照。",
    "opencode_cost_tip": "已记录 {amount} · 币种未知，显示为 N/A",
    "opencode_model_tip": "提供方 {provider} · 变体 {variant} · 智能体 {agent}",
    "total_unavailable_note": "OpenCode 记录 Total：已验证版本下五个原始分类之和；不是账单金额，也不是当前上下文大小，不可用时为 N/A",
}

EN = {
    "settings_title": "petoken · Settings", "save": "Save", "cancel": "Cancel",
    "language": "Display language", "language_zh_CN": "简体中文", "language_en": "English",
    "task_auto": "Automatically follow the current Codex task", "task_unnamed": "Untitled task",
    "task_selection": "Follow / pinned task", "token_scope": "Token and cost scope",
    "reset_defaults": "Reset to Defaults", "confirm_reset": "Click again to confirm reset",
    "token_number_format": "Token number format", "token_format_full": "Full",
    "token_format_compact": "Compact", "manual_fx": "Manual exchange rate (clear to use Bank of Canada)",
    "custom_price": "Override Standard pricing for the current model", "model_unrecorded": "Model not recorded",
    "price_input": "Regular input", "price_cached": "Cached input", "price_write": "Cache write",
    "price_output": "Output (including reasoning)",
    "about_data": "About the Data",
    "about_1_title": "Cost Estimate",
    "about_1_body": "The displayed cost is an API-equivalent estimate and does not represent your actual ChatGPT or Codex subscription charge.",
    "about_2_title": "Token Usage",
    "about_2_body": "Usage is calculated from readable local Codex records. Cache and context values are derived from available data; missing records may result in partial totals, and tool-call costs are not included.",
    "about_3_title": "Model & Reasoning",
    "about_3_body": "Model and reasoning values usually follow the first configuration recorded for the session. Launcher-side or mid-session changes may not always be fully captured.",
    "about_4_title": "Status & Privacy",
    "about_4_body": "Status priority: Codex Working ＞ Microphone ＞ Music ＞ Typing ＞ Idle. The panel opens beside the desktop pet. Petoken never stores keystroke content or persistently saves media subtitle text.",
    "settings_save_error": "Could not save settings. Check write permission for your user folder.",
    "scope_global": "Global", "scope_global_recorded": "Global (Locally Recorded)",
    "scope_project": "Project", "scope_conversation": "Conversation",
    "spirit_accessible": "Ice spirit", "connecting": "Connecting…",
    "collapse_expand": "Collapse / expand", "hide_to_tray": "Hide to system tray",
    "waiting_codex": "Waiting for Codex", "open_codex_task": "Open a task in Codex",
    "total_tokens": "TOTAL TOKENS", "input": "INPUT", "output": "OUTPUT",
    "switch_scope": "Switch usage scope", "analytics_button": "Token Analytics  ↗",
    "analytics_button_tip": "Open raw usage, derived metrics, models, conversations, and history",
    "context_used": "Context used", "five_hour_limit": "5-hour limit",
    "weekly_limit": "Weekly limit", "estimated_cost": "Estimated Cost",
    "currency": "Currency", "fx_unavailable_usd": "Exchange rate unavailable; showing USD.",
    "one_usd_equals": "1 USD = {rate} {currency}",
    "partial_estimate": "Partial Estimate", "always_on_top": "Always on Top",
    "character_size": "Character Size",
    "panel_pin": "Pin panel open", "panel_unpin": "Unpin panel",
    "checking_wait": "Checking every second · Waiting for data", "settings_help": "Settings and data notes",
    "tray_tip": "petoken · Double-click to show", "show_hide": "Show / hide",
    "show_hide_pet": "Show / hide desktop pet", "move_right": "Move to right side of screen",
    "exit_petoken": "Exit petoken", "settings_save_failed": "Settings could not be saved",
    "mode_follow": "● Following automatically", "mode_fixed": "◇ Pinned task", "mode_working": "● Working conversation",
    "mode_recent": "◌ Recently active · Foreground unknown", "waiting_data": "Waiting for data",
    "task_detection_tip": "The current task is identified from the Codex window accessibility title. If unavailable, the app explicitly falls back to recent activity; a task can also be pinned in Settings.",
    "waiting_available_task": "Waiting for an available task", "active_session": "Active session", "unnamed_task": "Untitled task",
    "model_not_recorded": "Model not recorded",
    "model_tip": "The most recently submitted model configuration. Menu changes may not be recorded until a message is sent.",
    "effort_tip": "Reasoning effort · Most recently submitted configuration",
    "no_reliable_record": "N/A · No reliable record", "cached_input_line": "Cached input: {value}",
    "output_includes_reasoning": "Reasoning output is already included and is not added again.",
    "context_tip": "Current task · {used} / {window} Tokens\nLatest recorded context use, not cumulative Tokens; it may differ slightly from the CLI reserved-space calculation.",
    "cache_hit_new_work": "Cache hit {ratio}  ·  New work {work}",
    "local_conversations": "{scope} · {count} local conversations",
    "known_price_usd": "Known-price portion USD ${usd}",
    "not_subscription_bill": "This is not a subscription bill. It converts recorded model and service-tier usage and excludes tool fees.",
    "unpriced_models": "No price for: {models} (add one in Settings)",
    "partial_records": "Some records are missing or reset, or inherited fork history was excluded.",
    "quota_unavailable": "This limit is unavailable for the current account.", "unknown": "Unknown",
    "account_quota": "Account limit · Remaining percentage", "reset_time": "Reset time: {reset}",
    "quota_stale": "Last recorded value; waiting to refresh", "quota_live": "Official endpoint · Queried every second",
    "left": "left", "stale": "stale", "awaiting_reset": "Waiting for the server to confirm reset",
    "reset_in": "Reset in {duration}", "quota_waiting": "Waiting for limit refresh",
    "syncing": "Syncing every second · {time}", "token_last_written": "Token last written {seconds} seconds ago",
    "no_token_events": "No Token events yet", "no_model_usage": "Reading local data does not call a model or consume model Tokens.",
    "quota_error": "Limits are temporarily unavailable; keeping the last value and retrying later.",
    "manual": "Manual", "custom": "Custom",
    "pet_title": "petoken · Skirk Desktop Pet",
    "pet_accessible": "Skirk desktop pet. Click to view usage, drag to move, or right-click for the menu.",
    "project_unavailable": "Project unavailable", "codex_working": "Codex Working",
    "pet_tooltip_tokens": "Total {total} · Input {input} · Output {output}",
    "pet_tooltip_actions": "Click to view usage · Drag to move · Right-click for menu",
    "working": "Working", "idle": "Idle", "context_short": "Ctx",
    "pet_toggle_panel": "Open / collapse usage panel", "pet_settings": "Settings and task selection",
    "idle_motion": "Idle motion", "hide_pet": "Hide desktop pet (restore from tray)", "exit": "Exit",
    "analytics_title": "petoken · Token Analytics", "analytics_heading": "TOKEN ANALYTICS · {scope}",
    "tab_full": "Full Usage", "tab_models": "By Model", "tab_conversations": "By Conversation",
    "tab_history": "Date && History", "tab_raw": "Raw Fields / Source",
    "header_group_metric": "Group / Metric", "header_exact": "Exact Value", "header_type_coverage": "Type / Coverage",
    "header_model": "Model", "header_conversation": "Conversation", "header_range": "Range",
    "header_date_local": "Date / Local Time", "records": "Records",
    "fx_rate_label": "1 USD = CAD",
    "header_input_tokens": "Input Tokens", "header_cached_tokens": "Cached Tokens",
    "header_uncached_tokens": "Uncached Tokens", "header_write_tokens": "Write Tokens",
    "header_output_tokens": "Output Tokens", "header_reasoning_tokens": "Reasoning Tokens",
    "header_nonreasoning_tokens": "Non-reasoning Tokens", "header_total_tokens": "Total Tokens",
    "analytics_subtitle": "{title} · {project} · {events:,} Records\nModels, conversations, dates, and history use the current scope. Global represents locally readable records only.",
    "history_initial": "Local indexed history · System local time; includes archived conversations. This is not complete server-account lifetime usage.",
    "history_loaded": "Local indexed history · Local time / calendar days · Excludes deleted, cloud-only, or unsynced records.",
    "history_partial": " Missing or excluded inherited history makes this a partial record.",
    "history_loading": "Reading local history incrementally…",
    "analytics_na_note": "N/A = reliable data is unavailable. Hover for formulas and exact sources; supported subtotals are shown separately.",
    "analytics_default_note": "Cached input and reasoning are subsets and are not added to Total again.",
    "raw": "raw", "derived": "derived", "known_subtotal": "known subtotal {value}",
    "total_source_coverage": "source total; falls back only to input + output when missing",
    "range_current": "Current session", "range_lifetime": "Local recorded lifetime", "range_today": "Today",
    "range_last7": "Last 7 calendar days", "range_last30": "Last 30 calendar days", "range_undated": "Undated / unallocated",
    "group_official": "Official OpenAI Usage", "group_cache": "Cache", "group_derived": "Derived Analytics", "group_comparison": "Comparison",
    "metric_total": "Total Tokens", "metric_input": "Input Tokens", "metric_cached": "Cached Input / Cache Read",
    "metric_uncached": "Uncached Input", "metric_output": "Output Tokens", "metric_reasoning": "Reasoning Tokens",
    "metric_nonreasoning": "Non-reasoning Output", "metric_cache_write": "Cache Write", "metric_cache_hit": "Cache Hit Ratio",
    "metric_new_work": "New / Non-cached Work", "metric_output_ratio": "Output Ratio", "metric_reasoning_ratio": "Reasoning Share of Output",
    "metric_comparison_uncached": "Input excluding cache read AND write", "metric_cache_read_component": "Cache Read component",
    "metric_cache_write_component": "Cache Write component", "metric_output_component": "Output component",
    "metric_claude_raw": "Claude-style Raw Processed", "metric_known_processed": "Supported processed subtotal",
    "unknown_model": "Unknown / Not recorded", "unknown_breakdown": "Unknown / missing Token breakdown",
    "raw_field_notes": "Unknown extra source fields are preserved here but are not interpreted or added to totals.",
    "help_total_tokens": "Official OpenAI total where available; otherwise input + output. Cached input is already inside input, and reasoning is already inside output.",
    "help_input_tokens": "Source input_tokens. Includes cached input and any reported cache-write input.",
    "help_cached_input_tokens": "Previously processed input reused from cache; a subset of input_tokens.",
    "help_uncached_input_tokens": "max(input − cached, 0). Input not served from cache; includes cache writes if reported.",
    "help_cache_write_input_tokens": "Source cache_write_input_tokens / cache_write_tokens only. Missing = N/A, not zero. A reported 0 is displayed as 0.",
    "help_output_tokens": "Source output_tokens. Already includes reasoning output.",
    "help_reasoning_output_tokens": "Reasoning Tokens reported as part of output usage; not added again to total.",
    "help_non_reasoning_output_tokens": "max(output − reasoning, 0).",
    "help_new_work": "Uncached input + output. Useful for separating newly processed work from repeated cached context.",
    "help_cache_hit_ratio": "cached ÷ input × 100. N/A if input is zero or a required field is missing.",
    "help_output_ratio": "output ÷ official total × 100. N/A if total is zero.",
    "help_reasoning_ratio": "reasoning ÷ output × 100. N/A if output is zero or reasoning is missing.",
    "help_comparison_uncached": "Comparison component: input − cache read − cache write. Writes are removed so the four components do not overlap.",
    "help_claude_raw": "Comparison only, not the official total. Non-cache/non-write input + cache read + cache write + output. OpenAI and Claude expose caching differently, so their headline totals should not be compared blindly. N/A when a component is unavailable.",
    "help_known_processed": "Supported subtotal: uncached input + cache read + output. Does not invent a cache-write split or add unknown writes.",
    "status_no_local_data": "No local Codex data found. Open a task in the client first.",
    "status_database_unavailable": "The Codex database is temporarily unreadable. Retrying next second.",
    "status_pinned_unavailable": "The pinned task is unavailable. Select it again.",
    "status_no_desktop_task": "No local desktop task is available yet.", "status_project_unavailable": "The current conversation has no reliable project identity.",
    "status_no_usage": "No local usage records are available yet.", "status_read_failed": "Reading temporarily failed. Retrying next second.",
    "display_all_usage": "All Codex Usage", "display_local_history": "Locally recorded history", "display_untitled": "Untitled conversation",
    "note_reset_missing_last": "Counter reset without a last-request record; the increment is unavailable.",
    "note_reset_used_last": "Cumulative counter reset: counted explicit last-request usage instead of the reset snapshot.",
    "note_reset_carry": "The reset snapshot contains untraceable carry; it was not added to avoid duplication.",
    "note_initial_carry": "The first snapshot contains earlier usage without timestamps or model; retained as unattributed carry.",
    "note_cache_write_unavailable": "Cache-write split is unavailable; cost excludes any unknown write premium.",
    "tracking_provider": "Tracking provider", "tracking_auto": "Auto", "tracking_codex": "Codex",
    "tracking_opencode": "OpenCode", "status_stale": "Stale",
    "analytics_provider_pending": "The current provider is OpenCode; analytics support arrives in a later update.",
    "analytics_heading_provider": "TOKEN ANALYTICS · {provider} · {scope}",
    "analytics_subtitle_opencode": "{title} · {project} · {count} local sessions · {freshness}",
    "group_opencode_raw": "OpenCode raw",
    "metric_recorded_cost": "Recorded Cost",
    "coverage_complete": "complete", "coverage_partial": "partial",
    "coverage_unknown": "unknown", "coverage_unavailable": "unavailable",
    "cost_recorded": "Recorded {amount} · currency unavailable",
    "history_cached_as_of": "Cached snapshot · as of {time}",
    "history_refresh_pending": "Refresh pending — showing the stable snapshot",
    "history_skipped_rows": "{count} malformed rows skipped — partial",
    "history_unavailable": "No daily history for this scope",
    "analytics_opencode_note": "N/A = no verified meaning. OpenCode shows raw categories plus a recorded Total for verified versions (not billing, not context); cost is a recorded amount with unknown currency.",
    "raw_source_opencode": "OpenCode SQLite session rollups + message metadata (no content)",
    "help_provider_analytics": "Analytics describes only the current provider and scope; switching clears stale data at once.",
    "help_recorded_cost": "Sum of recorded session amounts; sessions without amounts are excluded; currency unknown.",
    "help_unknown_currency": "The source has no currency field; amounts are never converted or labelled with a symbol.",
    "help_opencode_total": "Total is the five-category sum only for verified versions with complete data (a recorded total, not billing or context); missing, partial, or unverified versions stay N/A.",
    "help_partial_coverage": "Some sessions lack this category; only the known subtotal is shown and marked partial.",
    "help_cached_history": "Daily history aggregates message metadata; cached snapshots carry as_of and stay stable while pending.",
    "opencode_cost_tip": "Recorded {amount} · currency unstated, shown as N/A",
    "opencode_model_tip": "Provider {provider} · variant {variant} · agent {agent}",
    "total_unavailable_note": "OpenCode recorded Total: the five-category sum for verified versions; not a billed amount or current context size, N/A when unavailable",
}

STRINGS = {"zh_CN": ZH_CN, "en": EN}


def normalize_language(value):
    return value if value in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def text(key, language=DEFAULT_LANGUAGE, **values):
    language = normalize_language(language)
    template = STRINGS[language].get(key, STRINGS[DEFAULT_LANGUAGE].get(key, key))
    return template.format(**values) if values else template


def scope_text(scope, language=DEFAULT_LANGUAGE, recorded=False):
    scope = {"task": "conversation"}.get(scope, scope)
    key = "scope_global_recorded" if scope == "global" and recorded else f"scope_{scope}"
    return text(key if key in STRINGS[DEFAULT_LANGUAGE] else "scope_conversation", language)
