"""Central Simplified Chinese and English user-interface strings."""

DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES = ("zh_CN", "en")

ZH_CN = {
    "settings_title": "petoken · 设置", "save": "保存", "cancel": "取消",
    "language": "界面语言", "language_zh_CN": "简体中文", "language_en": "English",
    "task_auto": "自动跟随当前任务", "task_unnamed": "未命名任务",
    "task_selection": "跟随 / 固定任务", "token_scope": "Token 与费用范围",
    "reset_defaults": "恢复默认设置", "confirm_reset": "再次点击确认重置",
    "token_number_format": "Token 数字格式", "token_format_full": "完整数字",
    "token_format_compact": "紧凑格式", "manual_fx": "手动汇率（取消后使用加拿大央行）",
    "custom_price": "覆盖当前模型的 Standard 单价", "model_unrecorded": "模型尚未记录",
    "price_input": "普通输入", "price_cached": "缓存输入", "price_write": "缓存写入",
    "price_output": "输出（含 reasoning）",
    "about_data": "关于数据",
    "about_1_title": "费用估算",
    "about_1_body": "显示的是 API 等价费用估算，不代表 ChatGPT / Codex 或 Claude 订阅的实际扣费。",
    "about_2_title": "Token 统计",
    "about_2_body": "数据来自本地可读取的 Codex 和 Claude Code 记录。缓存、Context 等根据现有记录计算；缺失记录时，结果可能只是部分统计，且不包含工具调用费用。",
    "about_3_title": "模型与推理强度",
    "about_3_body": "模型和 reasoning 通常以会话首次记录的配置为准。通过启动器或会话中途修改的设置，不一定会被完整记录。",
    "about_4_title": "状态与隐私",
    "about_4_body": "状态优先级：Codex / Claude Code 工作 ＞ 麦克风 ＞ 音乐 ＞ 打字 ＞ 待机。浮窗会跟随桌宠展开。Petoken 不保存你输入的按键内容，也不会持久化保存媒体字幕内容。",
    "settings_save_error": "无法保存设置，请检查用户文件夹的写入权限。",
    "scope_global": "全局", "scope_global_recorded": "全局（本地记录）",
    "scope_project": "项目", "scope_conversation": "会话",
    "spirit_accessible": "冰晶小精灵", "connecting": "正在连接…",
    "collapse_expand": "收起 / 展开", "hide_to_tray": "隐藏到系统托盘",
    "waiting_codex": "等待任务", "open_codex_task": "打开 Codex 中的任务",
    "total_tokens": "TOTAL TOKENS", "input": "INPUT", "output": "OUTPUT",
    "switch_scope": "切换统计范围", "analytics_button": "Token Analytics  ↗",
    "analytics_button_tip": "展开完整原始用量、派生指标、模型、会话与历史",
    "context_used": "Context 已用", "five_hour_limit": "5 小时限额",
    "weekly_limit": "每周限额", "estimated_cost": "预估费用",
    "currency": "货币", "fx_unavailable_usd": "汇率暂不可用；以 USD 显示。",
    "one_usd_equals": "1 USD = {rate} {currency}",
    "partial_estimate": "部分估算", "always_on_top": "始终置顶",
    "character_size": "角色大小",
    "goal_unit_million": "百万 tokens",
    "goal_unit_billion": "十亿 tokens",
    "focus_todo_note": "选了待办，倒计时旁边会显示它，专注结束时可以一键把它勾掉。",
    "focus_break_length": "休息时长",
    "focus_long_break_length": "长休息时长",
    "focus_long_break_every": "每几轮来一次长休息",
    "focus_rounds_suffix": " 轮",
    "focus_no_break": "不休息",
    "focus_never": "不要长休息",
    "focus_pill_todo": "{todo} · {time}",
    "focus_todo_done": "这个待办做完了",
    "focus_line_focused": "专注在：{todo}",
    "preset_folder_fixed": "文件夹：{folder}（用项目自己的文件夹，在「编辑」里改）",
    "handoff_note_heading": "你上次留的话 · {ago}",
    "handoff_delete": "删除这条",
    "handoff_history": "以前的留言",
    "handoff_history_title": "{project} 的留言",
    "handoff_history_empty": "还没有留言。",
    "handoff_history_delete": "删除选中的",
    "todo_review_notice": "等你验收：{title}",
    "todo_review_notice_body": "AI 做完了。在工作台的待办里选中它，看看做了什么，再点通过或者再做一次。",
    "todo_review_button": "验收…",
    "todo_review_title": "验收 AI 的工作",
    "todo_review_intro": "{app} 做完了「{title}」。看看它做了什么：",
    "todo_review_no_note": "没有找到记录。可以打开项目文件夹看看改了什么。",
    "todo_review_feedback": "哪里还要改？（选「再做一次」时必填）",
    "todo_review_feedback_hint": "比如：按钮颜色不对，还要加上测试",
    "todo_review_need_feedback": "写一句哪里要改，AI 才知道再做什么。",
    "todo_review_accept": "通过",
    "todo_review_redo": "再做一次",
    "todo_redo_marker": "上次做完后我的意见：",
    "todo_redo_prompt": "上次做完后我的意见：{feedback}",
    "todo_ai_badge_review": "◎ {app} 做完了，等你验收",
    "wb_goal": "用量目标",
    "wb_goal_column": "本周用量 / 目标",
    "goal_title": "{project} 的每周用量目标",
    "goal_intro": "每周（周一开始）这个项目最多用多少。到 80% 她会着急，超出时提醒你一次；一周都没超出，她会很得意。按 token 或按 API 等价价格，填一个或两个都行。",
    "goal_tokens": "Token",
    "goal_usd": "金额（美元）",
    "goal_none": "不限",
    "goal_tokens_suffix": " 百万 tokens",
    "goal_worried": "「{project}」本周用量已到目标的 {percent}%",
    "goal_over": "「{project}」本周用量超出目标（{percent}%）",
    "goal_body": "可以在工作台的项目里看本周用量，或者调整目标。",
    "goal_proud": "上周「{project}」没超出用量目标，真棒！",
    "wb_collection": "收藏",
    "collection_intro": "陪伴点数来自完成待办、验收 AI 的工作、专注和按时休息，不按用掉多少 token 算。达成里程碑会得到纪念贴纸。",
    "collection_points": "陪伴点数：{points}",
    "collection_log": "最近的点数",
    "collection_log_line": "{when}  {reason}  +{points}",
    "collection_empty": "还没有点数。完成一个待办或者专注一轮试试。",
    "points_todo_done": "完成待办",
    "points_todo_accepted": "验收通过 AI 的工作",
    "points_focus_done": "完成一轮专注",
    "points_break_taken": "按时休息",
    "points_goal_week": "一周没超出用量目标",
    "sticker_earned": "获得纪念贴纸：{name}",
    "sticker_earned_on": "{date} 获得",
    "sticker_locked": "还没获得",
    "sticker_first_project": "第一个项目",
    "sticker_first_project_how": "完成一个属于某个项目的待办。",
    "sticker_first_weekly": "第一份周报",
    "sticker_first_weekly_how": "在报告里第一次打开「本周」。",
    "sticker_focus_10": "专注十次",
    "sticker_focus_10_how": "完成 10 轮专注。",
    "sticker_streak_7": "连续七天",
    "sticker_streak_7_how": "连续 7 天每天至少完成一轮专注。",
    "sticker_goal_week": "守住目标",
    "sticker_goal_week_how": "一个项目一整周都没超出用量目标。",
    "sticker_todos_100": "百个待办",
    "sticker_todos_100_how": "一共完成 100 个待办。",
    "preset_title": "{project} 的开工设置",
    "preset_prompt": "开场提示词（留空就用默认的：先看看项目现状、上次做到哪）",
    "preset_default_prompt": "先看看这个项目现在的状态，告诉我上次做到哪、接下来该做什么，然后等我确认再动手。",
    "preset_handoff_line": "我上次留的话：{note}",
    "preset_note": "点「开始工作」就会按这里的设置打开终端；你最近一次留的「下次从哪继续」会自动加在提示词后面。",
    "preset_save": "保存",
    "preset_start": "开始工作",
    "preset_need_folder": "这个项目还没有文件夹。先点「编辑」给项目选一个文件夹。",
    "wb_preset": "开工设置",
    "wb_continuation": "上次做到哪",
    "handoff_title": "回到 {project} · 上次做到哪",
    "handoff_note": "你上次留的话：{note}",
    "handoff_last_task": "上次 {app} 做的：{title}（{ago}）",
    "handoff_unfinished": "交给 AI 但没做完：{names}",
    "handoff_todos": "还有 {count} 个待办：{names}",
    "handoff_md": "项目里的 HANDOFF.md：",
    "handoff_placeholder": "给下次的自己留一句：从哪继续…",
    "handoff_save": "记下",
    "handoff_saved": "记下了，下次回来会提醒你",
    "handoff_empty": "这个项目还没有可以显示的：没有留言、待办和最近的任务。",
    "ago_minutes": "{n} 分钟前",
    "ago_hours": "{n} 小时前",
    "ago_days": "{n} 天前",
    "continuation_setting": "回到项目时提醒上次做到哪",
    "continuation_setting_tip": "隔了一段时间回到一个项目时，她会举着卡片告诉你上次做到哪。",
    "focus_menu": "开始专注",
    "focus_minutes": "{minutes} 分钟",
    "focus_hours": "{hours} 小时 {minutes} 分钟",
    "focus_custom": "选待办、调休息时间…",
    "focus_stop": "结束专注（还剩 {time}）",
    "focus_skip_break": "跳过休息",
    "focus_pill": "专注中 · {time}",
    "focus_pill_break": "休息中 · {time}",
    "focus_start_title": "开始专注",
    "focus_start_intro": "专注期间她会安静陪你，只有审批、出错、额度和上下文快满这类要紧的提醒会弹出来，其他的都记在「通知」里。",
    "focus_length": "时长",
    "focus_minute_suffix": " 分钟",
    "focus_project": "项目",
    "focus_todo": "专注在哪个待办（可选）",
    "focus_no_project": "不关联项目",
    "focus_no_todo": "不指定",
    "focus_start": "开始",
    "focus_done_title": "专注完成 · {time}",
    "focus_stopped_title": "专注结束 · {time}",
    "focus_line_todos": "完成了 {count} 个待办：{names}",
    "focus_line_ai": "AI 完成了 {count} 个任务",
    "focus_line_files": "改了 {count} 个文件",
    "focus_line_tokens": "用了 {tokens}",
    "focus_line_none": "这段时间没有记录到待办或 AI 任务。",
    "focus_counting": "正在统计文件和用量…",
    "focus_break_note": "现在休息 {minutes} 分钟，起来走走、喝口水。",
    "focus_again": "再专注一轮",
    "focus_card_close": "好的",
    "focus_break": "专注完成，休息 {minutes} 分钟",
    "focus_break_body": "起来走走、喝口水，她在这儿等你。",
    "focus_break_over": "休息结束",
    "focus_break_over_body": "想继续的话，右键她开始下一轮专注。",
    "report_focus": "专注 {count} 次，共 {time}",
    "clinginess": "粘人程度",
    "clinginess_quiet": "安静",
    "clinginess_moderate": "适中",
    "clinginess_clingy": "黏人",
    "clinginess_tip": "她自己做小动作的频率：安静只会睡觉和醒来；适中偶尔发呆、打哈欠、跟你打招呼；黏人更频繁，还会偷看你、向你撒娇。",
    "star_ring_enabled": "显示星环与任务星星",
    "panel_pin": "固定面板（保持展开）", "panel_unpin": "取消固定面板",
    "checking_wait": "每秒检查 · 等待数据", "settings_help": "设置与数据说明",
    "tray_tip": "petoken · 双击显示", "show_hide": "显示 / 隐藏",
    "show_hide_pet": "显示 / 隐藏桌宠", "move_right": "移回屏幕右侧",
    "exit_petoken": "退出 petoken", "settings_save_failed": "设置暂时无法保存",
    "mode_follow": "● 自动跟随", "mode_fixed": "◇ 已固定任务", "mode_working": "● 工作会话",
    "mode_recent": "◌ 最近活动 · 未识别前台", "waiting_data": "等待数据",
    "task_detection_tip": "Codex 通过窗口的辅助功能标题、Claude Code 通过会话登记识别当前任务。无法识别时明确退回最近活动；可在设置中固定。",
    "waiting_available_task": "等待可用任务", "active_session": "活动会话", "unnamed_task": "未命名任务",
    "model_not_recorded": "尚未记录模型",
    "model_tip": "最近一次已发送的模型配置。发送前的模型菜单改动可能尚未写入记录。",
    "effort_tip": "Reasoning effort · 最近一次已发送的配置",
    "no_reliable_record": "N/A · 没有可靠记录", "cached_input_line": "缓存输入：{value}",
    "output_includes_reasoning": "已包含 reasoning output，不重复相加。",
    "context_tip": "当前任务 · {used} / {window} Token\n最近一次记录的上下文占用，非累计 Token；与 CLI 的保留空间算法可能略有不同。",
    "cache_hit_new_work": "缓存命中 {ratio}  ·  新工作 {work}",
    "local_conversations": "{scope} · {count} 个本地会话",
    "known_price_usd": "已知单价部分 USD ${usd}",
    "not_subscription_bill": "不是订阅账单；按已记录的模型和服务档位折算，不含工具费用。",
    "unpriced_models": "尚无单价：{models}（可在设置中填写）",
    "partial_records": "部分记录缺失 / 重置，或排除了继承历史的 fork。",
    "quota_unavailable": "当前账户未提供此额度。", "unknown": "未知",
    "account_quota": "账户额度 · 剩余比例", "reset_time": "重置时间：{reset}",
    "quota_stale": "上次记录，等待刷新", "quota_live": "官方接口 · 每秒查询",
    "left": "剩余", "stale": "旧", "awaiting_reset": "等待服务端确认重置",
    "reset_in": "{duration} 后重置", "quota_waiting": "额度等待刷新", "quota_not_provided": "此来源不提供额度",
    "wb_notifications": "通知",
    "wb_notify_intro": "任务完成、出错、等待确认、额度不足和你的提醒都会记在这里，保留 30 天。双击「等待确认」可打开对应任务。",
    "wb_notify_open_hint": "双击打开这个任务",
    "wb_add_todo": "添加待办",
    "wb_todo_content": "内容",
    "wb_add_reminder": "添加提醒",
    "wb_reminder_repeat": "重复",
    "wb_reminder_time": "时间",
    "wb_reminder_todo": "关联待办",
    "wb_reminder_empty": "请先写提醒内容。",
    "wb_notify_all": "全部",
    "wb_notify_empty": "还没有通知。",
    "notify_kind_finished": "完成",
    "notify_kind_failed": "出错",
    "notify_kind_needs_approval": "等待确认",
    "notify_kind_quota_low": "额度不足",
    "notify_kind_reminder": "提醒",
    "notify_kind_forecast": "额度预测",
    "notify_kind_context_full": "上下文快满",
    "notify_kind_stuck": "可能卡住",
    "notify_kind_quota_back": "额度恢复",
    "notify_forecast": "{provider} 的 5 小时额度预计 {time} 后用完",
    "notify_forecast_switch": "{other} 还有不少额度，可以先切过去",
    "notify_context_full": "{provider} 的上下文快满了",
    "notify_context_full_body": "只剩 {left}%：可以用 /compact 压缩，或开一个新对话",
    "notify_stuck": "{provider} 的任务已经 {minutes} 分钟没有进展",
    "notify_quota_back": "{provider} 的额度恢复了，可以继续了",
    "approval_setting": "在桌宠上批准 Claude",
    "approval_setting_tip": "开启后，Claude Code 请求权限（运行命令、改文件等）时，桌宠旁边会弹出卡片：允许、以后都允许、拒绝，或者交回 Claude 自己处理。{wait} 秒内没有回答，或者 Petoken 没在运行，Claude Code 会像平常一样自己问你。会在 Claude Code 设置里加入一个 hook（先备份），关闭时只移除这一个。",
    "approval_rules": "已允许的规则…",
    "approval_rules_title": "「以后都允许」的规则",
    "approval_rules_intro": "这些是你在桌宠上选「以后都允许」时，Claude Code 保存到各项目 .claude/settings.local.json 里的规则。撤销后，下次会重新询问。",
    "approval_rules_empty": "还没有规则。",
    "approval_revoke": "撤销",
    "approval_rules_close": "关闭",
    "approval_title_shell": "{provider} 想运行命令",
    "approval_title_edit": "{provider} 想修改文件",
    "approval_title_web": "{provider} 想访问网络",
    "approval_title_tool": "{provider} 想使用 {tool}",
    "approval_project": "项目：{project}",
    "plan_title": "{provider} 提出了一个计划",
    "plan_open": "打开计划文件",
    "plan_feedback": "要改什么？（可选，点「修改」时发给 Claude）",
    "plan_revise": "修改",
    "plan_accept": "接受",
    "plan_accept_edits": "接受并允许编辑",
    "plan_accept_edits_tip": "接受计划，这次会话里改文件不再逐个询问（和 Claude 里的同名选项一样）。",
    "question_title": "{provider} 有问题想问你",
    "question_other": "或者自己写答案",
    "question_multi": "多选题可以选多个。",
    "question_submit": "回答",
    "question_countdown": "{time} 后交回 Claude",
    "approval_allow": "允许",
    "approval_always": "以后都允许",
    "approval_deny": "拒绝",
    "approval_ask": "在 Claude 里回答",
    "approval_countdown": "{seconds} 秒后交回 Claude",
    "approval_more": "还有 {count} 个",
    "approval_always_tip": "以后在「{project}」里不再询问：{rule}",
    "approval_always_unavailable": "这个请求太长或有多行，只能单次允许",
    "recap_files": "改了 {count} 个文件",
    "recap_no_files": "没有改文件",
    "launch_menu": "快速派活…",
    "launch_chat": "只是聊聊（不在项目里干活）",
    "launch_chat_tip": "不用选文件夹：在 Petoken 专用的空文件夹里开一个对话，适合问问题、讨论想法，不会碰你的项目文件。",
    "launch_model": "模型",
    "launch_effort": "推理强度",
    "launch_model_default": "默认（跟随这个 App 的设置）",
    "launch_effort_default": "默认（跟随这个 App 的设置）",
    "launch_options_unavailable": "这个 App 暂时只能用它自己的默认设置",
    "launch_effort_none": "这个模型没有推理强度可选",
    "launch_model_credits_badge": "需要额外用量额度",
    "launch_bad_choice": "这个 App 不支持这个模型和推理强度的组合，请换一个。",
    "launch_title": "快速派活",
    "launch_prompt": "要做什么？",
    "launch_prompt_hint": "例如：给网站加上深色模式",
    "launch_folder": "项目文件夹",
    "launch_browse": "浏览…",
    "launch_app_missing": "没有找到这个 App 的命令行（需要安装 Claude Code 或 Codex 的命令行版本）",
    "launch_note": "会在新终端里开始，权限照常询问；开始后它会变成一颗星星。",
    "launch_cancel": "取消",
    "launch_start": "开始",
    "launch_need_prompt": "先写下要做什么。",
    "launch_need_folder": "请选择一个存在的项目文件夹。",
    "launch_too_long": "内容太长，Windows 命令行放不下，请缩短一些。",
    "launch_failed": "没能打开终端。",
    "launch_hotkey": "快速派活快捷键",
    "launch_hotkey_tip": "在任何地方按 {combo} 打开快速派活：写下要做什么、选项目和 App，就会在新终端里开始。也可以从桌宠右键菜单或托盘菜单打开。",
    "launch_hotkey_taken": "{combo} 和其他备选快捷键都被别的程序占用了，请用右键菜单打开。",
    "launch_hotkey_moved": "{combo} 已被别的程序占用，现在用的是 {active}。",
    "launch_hotkey_off": "关闭",
    "wb_reports": "报告",
    "report_intro": "AI 今天或本周帮你做了多少：完成的任务、工作时长、改过的文件、用量和费用。全部来自本机数据；费用是按 API 价格估算的等价费用，不是订阅账单。",
    "report_today": "今天",
    "report_week": "本周",
    "report_reload": "重新统计",
    "report_loading": "正在统计…",
    "report_updating": "正在更新…",
    "report_updated": "{time} 更新",
    "report_tile_tasks": "处理的任务",
    "report_tile_time": "AI 工作时长",
    "report_tile_files": "改过的文件",
    "report_tile_time_tip": "Claude Code 和 Codex 每一轮从你提问到回复完成的时间之和（几个任务同时进行时会叠加）。",
    "report_tile_files_tip": "Claude Code 和 Codex 成功修改过的文件。用命令行脚本改的文件不计入。",
    "report_tile_tokens": "Tokens",
    "report_tile_cost": "等价 API 费用",
    "report_tile_change": "用量比上期",
    "report_outcomes": "Petoken 记下的结果：完成 {finished} 个，出错 {failed} 个",
    "report_cost_note": "按 API 价格估算的等价费用，不是订阅账单。",
    "report_cost_partial": "有些回复的模型价格未知，没算进去，实际会更多。",
    "report_provider_line": "{app}：{tasks} 个任务 · {tokens} · {cost}",
    "report_projects": "用得最多的项目：{projects}",
    "report_missing": "没能读取：{apps}",
    "report_empty": "这段时间还没有记录。",
    "report_history": "历史任务",
    "report_search": "搜索标题或项目",
    "report_range_week": "最近 7 天",
    "report_range_month": "最近 30 天",
    "report_range_all": "全部",
    "report_col_when": "时间",
    "report_col_app": "App",
    "report_col_title": "标题",
    "report_col_project": "项目",
    "report_col_tokens": "Tokens",
    "report_col_cost": "费用",
    "update_setting": "更新",
    "update_check": "每天检查新版本",
    "update_auto_short": "自动安装",
    "update_check_now": "立即检查",
    "update_tip": "每天向 GitHub 读取一次最新版本信息（不发送这台电脑的任何信息）。有新版本时会告诉你更新了什么；勾选「自动安装」后，会在没有任务运行时自动下载、核对校验值并安装，装完自动重新打开，设置和数据都保留。",
    "update_title": "Petoken {version} 可以更新了",
    "update_heading": "新版本 {version} 已发布（你现在用的是 {current}）。下面是更新内容：",
    "update_no_notes": "这个版本没有写更新说明。",
    "update_auto": "以后自动更新（在没有任务运行时安装）",
    "update_skip": "跳过这个版本",
    "update_later": "以后再说",
    "update_now": "现在更新",
    "update_downloading": "正在下载并核对校验值，完成后 Petoken 会关闭、安装，然后自动重新打开……",
    "update_failed": "更新没有完成，原来的版本不受影响",
    "update_none": "已经是最新版本（{version}）",
    "update_check_failed": "暂时连不上 GitHub，稍后再试",
    "onboarding_setting": "新手引导",
    "onboarding_open": "重新打开…",
    "onboard_welcome_title": "欢迎使用 Petoken",
    "onboard_welcome_body": "Petoken 是住在桌面上的 AI 编程小伙伴：跟着你的 Codex 和 Claude Code 任务，显示用量、额度和费用，任务完成或需要你时提醒你，还能在人物旁边直接回复 Claude。接下来用一分钟把常用功能打开。所有数据都只留在这台电脑上。",
    "onboard_claude_title": "Claude Code",
    "onboard_claude_body": "检测到你在用 Claude Code。下面这些功能会修改 Claude Code 的设置文件（修改前会先备份，保留你自己的设置），以后随时可以在 设置 → Claude 里关掉。",
    "onboard_claude_sync": "同步 Claude 用量",
    "onboard_claude_sync_note": "加一条状态栏命令，显示 Pro/Max 的 5 小时和每周额度。只记录用量数字。",
    "onboard_claude_notify": "Claude 即时通知",
    "onboard_claude_notify_note": "加几个 hook，任务完成、出错或等你确认时 1 秒内提醒你。只记录事件类型和时间。",
    "onboard_claude_approval": "在桌宠上批准 Claude",
    "onboard_claude_approval_note": "Claude 要权限、提问或提交计划时，人物旁边弹出卡片让你直接回复。Petoken 没开时一切照旧。",
    "onboard_mute_claude_toasts": "Petoken 运行时关闭 Claude 桌面版的弹窗",
    "onboard_mute_claude_toasts_note": "避免同一件事弹两次；退出 Petoken 时恢复你原来的设置。",
    "onboard_codex_title": "Codex",
    "onboard_codex_body": "检测到你在用 Codex。Codex 的用量和额度不需要设置就能看到；下面这个功能会修改 Codex 的 hooks.json（先备份），以后可以在 设置 → Claude 和 Codex 里关掉。",
    "onboard_codex_note": "Codex 任务完成或等你批准时马上提醒你，批准请求也能在桌宠旁边处理。需要在 Codex 里输入 /hooks 信任一次，新会话生效。",
    "onboard_assistant_title": "省时间的小助手",
    "onboard_assistant_body": "快捷键可以在任何地方打开「快速派活」，写下要做什么就会让 Claude 或 Codex 在新终端里开工。预测和建议会提前告诉你额度什么时候用完。",
    "onboard_done_title": "准备好了",
    "onboard_done_body": "点人物打开用量面板，拖动可以移动；右键人物有快速派活、工作台、报告和设置。有新版本时 Petoken 会告诉你。这个引导以后可以在 设置 → 常规 里重新打开。",
    "onboard_tutorial": "接着打开工作台的新手教程",
    "onboard_skip": "跳过",
    "onboard_back": "上一步",
    "onboard_next": "下一步",
    "onboard_finish": "完成",
    "todo_ai_button": "交给 AI…",
    "todo_ai_title": "把待办交给 AI",
    "todo_ai_prompt": "要 AI 做什么？（默认是待办的标题，可以写得更具体）",
    "todo_ai_now": "现在开始",
    "todo_ai_at": "定时：",
    "todo_ai_note": "到时间后会在新终端里开始，权限照常询问（或者在桌宠上批准）。AI 做完后会写一条便签记录它做了什么，这条待办进入「等你验收」：你看过之后点通过才算完成。",
    "todo_ai_take_back": "收回",
    "todo_ai_take_back_tip": "不再交给 AI：取消定时，或者停止跟踪正在做的任务（已经打开的终端不会被关掉）。",
    "todo_ai_lost": "有 {count} 个交给 AI 的待办没找到对应的任务",
    "todo_ai_lost_body": "终端可能没能启动或者被关掉了。可以在待办里重新交给 AI。",
    "todo_ai_ok": "确定",
    "todo_ai_badge_waiting": "⏰ {when} · {app}",
    "todo_ai_badge_started": "▶ {app} 正在做",
    "todo_ai_badge_finished": "✓ {app} 已完成（见便签）",
    "todo_ai_badge_failed": "⚠ {app} 出错了或没能启动",
    "todo_ai_badge_missed": "⏸ 错过了时间：选中后点「交给 AI…」重新开始",
    "todo_ai_missed": "有 {count} 个定时待办错过了时间",
    "todo_ai_missed_body": "Petoken 或电脑当时没开。到工作台的待办里选择现在运行或取消。",
    "todo_ai_note_title": "AI 完成：{title}",
    "todo_ai_note_intro": "{app} 完成了待办「{title}」。",
    "todo_ai_note_prompt": "要求：{prompt}",
    "todo_ai_note_folder": "文件夹：{folder}",
    "todo_ai_note_summary": "小结：{summary}",
    "todo_ai_note_files": "改过的文件：",
    "todo_ai_note_check": "请检查一下结果是否符合预期；有问题可以把这条待办重新交给 AI。",
    "schedule_missed": "错过的定时待办",
    "schedule_missed_ask": "下次打开时提醒我",
    "schedule_missed_run": "自动补跑",
    "schedule_missed_tip": "Petoken 或电脑在定时的时间没开时怎么处理：提醒你自己决定，或者打开后立刻开始。",
    "codex_hooks": "Codex 即时通知和桌宠批准",
    "codex_hooks_tip": "开启后，Petoken 会在 Codex 的 hooks.json 里加入几个 hook（先备份，保留你自己的 hook）：Codex 任务完成或等你批准时马上提醒你，批准请求也会出现在桌宠旁边（只能单次允许或拒绝）。Codex 要求你在 Codex 里用 /hooks 信任一次这些 hook，并在新会话里生效。Petoken 没开时 Codex 照常自己询问。",
    "menu_more": "更多",
    "diagnostics_export": "导出诊断信息…",
    "diagnostics_tip": "遇到问题时导出一个 zip，附在 GitHub Issue 里，方便定位。导出前会先显示里面的全部内容。",
    "diagnostics_intro": "下面就是会保存进 zip 的全部内容：版本、各功能开关、错误日志、审批步骤日志和最近 7 天的通知数量。不包含对话内容、文件内容、命令、文件夹路径或任何账号信息。确认没问题再点「保存」。",
    "diagnostics_saved": "已保存到 {path}",
    "diagnostics_failed": "保存失败，请换一个位置再试。",
    "mute_claude_toasts": "Petoken 运行时关闭 Claude 桌面版的弹窗",
    "mute_claude_toasts_tip": "避免同一件事弹两次：Petoken 运行时，关闭 Claude 桌面版自己的 Windows 通知（和「Windows 设置 → 系统 → 通知 → Claude」是同一个开关）；退出 Petoken 或取消勾选时恢复你原来的设置。不需要管理员权限。",
    "settings_page_general": "常规",
    "settings_page_tracking": "任务",
    "settings_page_claude": "Claude 和 Codex",
    "settings_page_assistant": "助手与通知",
    "settings_page_about": "关于数据",
    "assistant_hints": "预测和建议",
    "assistant_hints_tip": "根据你现在的用量速度，预测额度什么时候用完、建议切换到额度更多的 App，并在上下文快满、任务长时间没有进展、额度恢复时提醒你。全部在本机计算。",
    "hint_out": "额度用完了，重置后才能继续",
    "hint_out_switch": "额度用完了 · 可以先用 {other}",
    "hint_run_out": "按现在的速度，约 {time} 后用完",
    "hint_run_out_switch": "约 {time} 后用完 · 可以切到 {other}",
    "hint_context_full": "上下文只剩 {left}%，建议 /compact",
    "hint_week_run_out": "本周额度约 {time} 后用完",
    "hint_stuck": "已经 {minutes} 分钟没有进展",
    "wb_reminders": "个人提醒",
    "wb_reminder_placeholder": "提醒内容，例如：看看 Codex 的结果",
    "wb_repeat_once": "一次",
    "wb_repeat_daily": "每天",
    "wb_repeat_weekly": "每周",
    "wb_reminder_no_todo": "不关联待办",
    "wb_reminder_past": "这个时间已经过去了，请选一个以后的时间。",
    "wb_reminder_done": "已提醒",
    "wb_every_day": "每天 {time}",
    "wb_every_week": "每周{day} {time}",
    "wb_weekday_names": "一,二,三,四,五,六,日",
    "claude_notify": "Claude 即时通知",
    "claude_notify_tip": "开启后，Petoken 会在 Claude Code 设置里加入几个 hooks，Claude 回复完成、出错或等你确认时立即通知你（命令行和桌面版都有效）。只记录事件类型和时间，不记录对话内容。会先备份原设置，关闭时只移除 Petoken 加的部分。关闭时仍会通过定期检查提醒任务完成，但会慢几秒。\n提示：Claude 桌面版自己也会弹完成通知；勾选下面的「Petoken 运行时关闭 Claude 桌面版的弹窗」就只会收到 Petoken 这一条。",
    "dnd": "免打扰",
    "dnd_scheduled": "定时免打扰",
    "dnd_tip": "免打扰期间不弹通知、桌宠不做反应，但通知仍会记录在工作台的「通知」里。",
    "notify_finished": "{provider} 任务完成",
    "notify_failed": "{provider} 任务出错了",
    "notify_needs_approval": "{provider} 在等你确认",
    "notify_quota_low": "{provider} 5 小时额度只剩 {left}%",
    "notify_reminder": "提醒",
    "usage_context": "上下文",
    "usage_five_hour": "5 小时",
    "usage_week": "1 周",
    "usage_remaining": "剩余",
    "usage_quota_unknown": "暂时没有额度数据",
    "usage_quota_waiting_codex": "正在读取额度…",
    "usage_claude_sync_on": "下次回复后显示额度",
    "usage_claude_sync_off": "在设置中开启「同步 Claude 用量」",
    "claude_usage_sync": "同步 Claude 用量",
    "claude_usage_sync_tip": "开启后，Petoken 会在 Claude Code 设置里加一条状态栏命令，用来读取 5 小时、1 周用量和 context。只保存数字，不保存对话内容。需要 Claude Pro/Max；会先备份原设置，关闭时会移除。",
    "claude_usage_sync_foreign": "Claude Code 已经有自定义状态栏，Petoken 不会覆盖它。",
    "claude_usage_sync_unreadable": "读取不了 Claude Code 的设置文件，所以没有改动。",
    "claude_quota_updated": "Claude 用量 · {time} 更新（Claude Code 回复时同步）",
    "claude_quota_waiting": "Claude 用量同步已开启 · 等待 Claude Code 下一次回复（需 Pro/Max）",
    "claude_quota_off": "Claude 用量未同步 · 可在设置中开启",
    "compat_partial": "部分兼容", "compat_unsupported": "格式无法识别",
    "compat_partial_tip": "Codex 本地数据有部分结构未能识别：相关数字显示 N/A，其余照常。",
    "compat_unsupported_tip": "Codex 本地数据格式无法识别（可能是 Codex 更新了），用量暂不可用。",
    "compat_version": "Codex 版本：{version}",
    "syncing": "每秒同步 · {time}", "token_last_written": "Token 最近写入：{seconds} 秒前",
    "no_token_events": "尚无 Token 事件", "no_model_usage": "读取不会调用模型或消耗模型 Token。",
    "quota_error": "额度暂不可用；保留上次读数，稍后重试。",
    "manual": "手动", "custom": "自定义",
    "pet_title": "petoken · 丝柯克桌宠",
    "pet_accessible": "丝柯克桌宠。点击展开用量，拖动移动，右键打开菜单。",
    "project_unavailable": "项目不可用", "codex_working": "Codex 工作中", "claude_working": "Claude Code 工作中",
    "pet_tooltip_tokens": "总计 {total} · 输入 {input} · 输出 {output}",
    "pet_tooltip_actions": "点击展开用量 · 拖动移动 · 右键菜单",
    "working": "工作中", "idle": "空闲", "context_short": "Ctx",
    "pet_toggle_panel": "打开 / 收起用量面板", "pet_settings": "设置与任务选择",
    "idle_motion": "待机动作", "hide_pet": "隐藏桌宠（托盘可恢复）", "exit": "退出",
    "analytics_title": "petoken · Token Analytics", "analytics_heading": "TOKEN ANALYTICS · {scope}",
    "tab_full": "完整用量", "tab_models": "按模型", "tab_conversations": "按会话",
    "tab_history": "日期与历史", "tab_raw": "原始字段 / 来源",
    "header_group_metric": "分组 / 指标", "header_exact": "精确值", "header_type_coverage": "类型 / 覆盖范围",
    "header_model": "模型", "header_conversation": "会话", "header_range": "范围",
    "header_date_local": "日期 / 本地时区", "records": "记录",
    "fx_rate_label": "1 USD = CAD",
    "header_input_tokens": "Input Tokens", "header_cached_tokens": "Cached Tokens",
    "header_uncached_tokens": "Uncached Tokens", "header_write_tokens": "Write Tokens",
    "header_output_tokens": "Output Tokens", "header_reasoning_tokens": "Reasoning Tokens",
    "header_nonreasoning_tokens": "Non-reasoning Tokens", "header_total_tokens": "Total Tokens",
    "analytics_subtitle": "{title} · {project} · {events:,} 条记录\n模型、会话、日期与历史均使用当前统计范围；全局仅代表本地可读取记录。",
    "history_initial": "本地索引历史 · 按系统本地时区；包括已归档会话。不是服务器账户的完整 lifetime。",
    "history_loaded": "本地索引历史 · 本地时区 / 日历天 · 不包括已删除、云端独有或未同步的记录。",
    "history_partial": " 存在缺失或已排除的继承历史，请视为部分记录。",
    "history_loading": "正在增量读取本地历史…",
    "analytics_na_note": "N/A = 缺少可靠数据。鼠标悬停查看公式与精确来源；部分已知小计会单独标注。",
    "analytics_default_note": "缓存输入与 reasoning 均为子项，不会再次计入 Total。",
    "raw": "原始", "derived": "派生", "known_subtotal": "已知小计 {value}",
    "total_source_coverage": "来源 total；缺失时仅以 input + output 回退",
    "range_current": "当前会话", "range_lifetime": "本地记录 lifetime", "range_today": "今天",
    "range_last7": "最近 7 个日历日", "range_last30": "最近 30 个日历日", "range_undated": "无日期 / 未分配",
    "group_official": "Official OpenAI", "group_cache": "Cache", "group_derived": "Derived", "group_comparison": "Comparison",
    "metric_total": "Total Tokens", "metric_input": "Input Tokens", "metric_cached": "Cached Input / Cache Read",
    "metric_uncached": "Uncached Input", "metric_output": "Output Tokens", "metric_reasoning": "Reasoning Tokens",
    "metric_nonreasoning": "Non-reasoning Output", "metric_cache_write": "Cache Write", "metric_cache_hit": "Cache Hit Ratio",
    "metric_new_work": "新工作 / 非缓存工作", "metric_output_ratio": "输出占比", "metric_reasoning_ratio": "Reasoning 输出占比",
    "metric_comparison_uncached": "不含 cache read 与 write 的输入", "metric_cache_read_component": "Cache Read 分量",
    "metric_cache_write_component": "Cache Write 分量", "metric_output_component": "输出分量",
    "metric_claude_raw": "Claude-style Raw Processed", "metric_known_processed": "可支持的 processed 小计",
    "unknown_model": "未知 / 未记录", "unknown_breakdown": "未知 / 缺少 Token 明细",
    "raw_field_notes": "未识别的额外源字段会保留在此处，但不会被解释或计入总数。",
    "help_total_tokens": "优先使用 OpenAI 官方 total；缺失时采用 input + output。缓存输入已包含在 input 中，reasoning 已包含在 output 中。",
    "help_total_tokens_claude": "Claude Code：总量 = 输入 + 输出。输入已包含缓存读取和缓存写入，思考 token 已包含在输出中。",
    "help_input_tokens": "来源 input_tokens，包含缓存输入及来源报告的 cache-write 输入。",
    "help_cached_input_tokens": "从缓存复用的已处理输入，是 input_tokens 的子项。",
    "help_uncached_input_tokens": "max(input − cached, 0)。未由缓存提供的输入；若报告 cache write，也包含在内。",
    "help_cache_write_input_tokens": "仅使用来源 cache_write_input_tokens / cache_write_tokens。缺失显示 N/A，不替换为 0；来源报告 0 时显示 0。",
    "help_output_tokens": "来源 output_tokens，已包含 reasoning 输出。",
    "help_reasoning_output_tokens": "来源报告的 reasoning Token，是输出用量的子项，不会再次加入总数。",
    "help_non_reasoning_output_tokens": "max(output − reasoning, 0)。",
    "help_new_work": "未缓存输入 + 输出，用于区分新处理的输入与重复缓存上下文。",
    "help_cache_hit_ratio": "cached ÷ input × 100。input 为 0 或必要字段缺失时显示 N/A。",
    "help_output_ratio": "output ÷ 官方 total × 100。total 为 0 时显示 N/A。",
    "help_reasoning_ratio": "reasoning ÷ output × 100。output 为 0 或 reasoning 缺失时显示 N/A。",
    "help_comparison_uncached": "对比分量：input − cache read − cache write。此处扣除 write，使四个对比分量互不重叠。",
    "help_claude_raw": "仅用于比较，不是 OpenAI 官方总数。非缓存/非 write 输入 + cache read + cache write + output。OpenAI 与 Claude 的缓存口径不同，不应直接比较 headline 总数；任一分量缺失时显示 N/A。",
    "help_known_processed": "可支持的小计：未缓存输入 + cache read + output。不会虚构 cache-write 明细或加入未知 write。",
    "status_no_local_data": "未找到 Codex 本地数据，请先在客户端打开一个任务。",
    "status_database_unavailable": "Codex 数据库暂时不可读，下一秒重试。",
    "status_pinned_unavailable": "固定的任务已不可用，请重新选择。",
    "status_no_desktop_task": "还没有本地桌面任务。", "status_project_unavailable": "当前会话没有可靠的项目身份。",
    "status_no_usage": "还没有本地用量记录。", "status_read_failed": "读取暂时失败，下一秒重试。",
    "display_all_usage": "全部用量", "display_local_history": "本地记录历史", "display_untitled": "未命名会话",
    "note_reset_missing_last": "计数器重置但缺少 last-request 记录；无法取得增量。",
    "note_reset_used_last": "累计计数器已重置：采用明确的 last-request 用量，不计重置快照。",
    "note_reset_carry": "重置快照含无法追踪的继承量；为避免重复未计入。",
    "note_initial_carry": "首个快照含更早且无时间/模型的用量；已作为未归属继承量保留。",
    "note_cache_write_unavailable": "Cache-write 明细不可用；费用未包含未知的 write 溢价。",
    "tracking_provider": "跟踪提供方", "tracking_auto": "自动", "tracking_codex": "Codex",
    "tracking_opencode": "OpenCode", "status_stale": "已过期",
    "tracking_claude": "Claude Code",
    "status_claude_no_local_data": "未找到 Claude Code 本地数据，请先在 Claude Code 中打开一个会话。",
    "analytics_provider_pending": "当前提供方为 OpenCode，分析视图将在后续更新中支持。",
    "analytics_heading_provider": "TOKEN ANALYTICS · {provider} · {scope}",
    "analytics_subtitle_opencode": "{title} · {project} · {count} 个本地会话 · {freshness}",
    "group_opencode_raw": "OpenCode 原始",
    "metric_recorded_cost": "已记录费用",
    "coverage_complete": "完整", "coverage_partial": "部分",
    "coverage_unknown": "未知", "coverage_unavailable": "不可用",
    "cost_recorded": "已记录 {amount} · 币种未知",
    "history_cached_as_of": "缓存快照 · 更新于 {time}",
    "history_refresh_pending": "有更新待刷新 —— 显示稳定快照",
    "history_skipped_rows": "已跳过 {count} 条异常记录 —— 部分统计",
    "history_unavailable": "此范围暂无日期历史",
    "analytics_opencode_note": "N/A = 没有验证口径。OpenCode 显示原始分类，对已验证版本另有记录 Total（非账单、非上下文）；费用为已记录金额，币种未知。",
    "raw_source_opencode": "OpenCode SQLite 会话汇总 + 消息元数据（不含内容）",
    "help_provider_analytics": "分析视图只描述当前来源与范围；切换范围会立即清空旧数据。",
    "help_recorded_cost": "会话汇总中已记录的金额之和；缺失会话不计入，币种未知。",
    "help_unknown_currency": "来源没有币种字段；金额不换算、不标注币种符号。",
    "help_opencode_total": "已验证版本且五个分类完整时，Total 为五个原始分类之和（记录 Total，非账单、非上下文）；缺失、部分或未验证版本时为 N/A。",
    "help_partial_coverage": "部分会话缺失该分类，只显示已知小计并标注部分。",
    "help_cached_history": "日期历史来自消息元数据聚合；缓存快照标明 as_of，待刷新时保持显示稳定快照。",
    "opencode_cost_tip": "已记录 {amount} · 币种未知，显示为 N/A",
    "opencode_model_tip": "提供方 {provider} · 变体 {variant} · 智能体 {agent}",
    "total_unavailable_note": "OpenCode 记录 Total：已验证版本下五个原始分类之和；不是账单金额，也不是当前上下文大小，不可用时为 N/A",
    "provider_mode_auto": "提供方：自动",
    "provider_mode_manual": "提供方：手动 · {provider}",
    "task_panel_label": "活动任务 {n}",
    "task_panel_total": "总计",
    "task_panel_input": "输入",
    "task_panel_output": "输出",
    "task_panel_reasoning": "推理",
    "task_panel_cache_read": "缓存读取",
    "task_panel_cache_write": "缓存写入",
    "task_panel_model": "模型",
    "task_panel_cost": "已记录费用",
    "task_panel_effort": "推理强度",
    "task_panel_variant": "模型变体",
    "task_panel_context": "上下文",
    "task_collapse": "收起任务详情",
    "task_go_to_window": "前往这个任务的窗口",
    "task_accessible": "{label} · {provider} · 按 Enter 查看详情",
    "usage_panel": "用量面板（常驻显示）",
    "panel_pinned_help": "勾选后，用量面板会一直显示并置顶，不会自动隐藏；取消勾选即恢复为鼠标悬停时显示。每次启动软件时默认不勾选。",
    "close_unpins_hub": "关闭用量面板（同时取消保持打开）",
    "task_overview": "活动任务 · {count}",
    "task_metric_scope": "用量：{provider} · {scope}",
    "task_source_unavailable": "用量来源不可用；已知记录可能不完整。",
    "task_usage_unavailable": "暂无已验证用量。",
    "task_record_note": "记录存在限制；仅显示已知用量。",
    "reset_task_layout": "重置任务布局",
}

EN = {
    "settings_title": "petoken · Settings", "save": "Save", "cancel": "Cancel",
    "language": "Display language", "language_zh_CN": "简体中文", "language_en": "English",
    "task_auto": "Automatically follow the current task", "task_unnamed": "Untitled task",
    "task_selection": "Follow / pinned task", "token_scope": "Token and cost scope",
    "reset_defaults": "Reset to Defaults", "confirm_reset": "Click again to confirm reset",
    "token_number_format": "Token number format", "token_format_full": "Full",
    "token_format_compact": "Compact", "manual_fx": "Manual exchange rate (clear to use Bank of Canada)",
    "custom_price": "Override Standard pricing for the current model", "model_unrecorded": "Model not recorded",
    "price_input": "Regular input", "price_cached": "Cached input", "price_write": "Cache write",
    "price_output": "Output (including reasoning)",
    "about_data": "About the Data",
    "about_1_title": "Cost Estimate",
    "about_1_body": "The displayed cost is an API-equivalent estimate and does not represent your actual ChatGPT, Codex or Claude subscription charge.",
    "about_2_title": "Token Usage",
    "about_2_body": "Usage is calculated from readable local Codex and Claude Code records. Cache and context values are derived from available data; missing records may result in partial totals, and tool-call costs are not included.",
    "about_3_title": "Model & Reasoning",
    "about_3_body": "Model and reasoning values usually follow the first configuration recorded for the session. Launcher-side or mid-session changes may not always be fully captured.",
    "about_4_title": "Status & Privacy",
    "about_4_body": "Status priority: Codex / Claude Code Working ＞ Microphone ＞ Music ＞ Typing ＞ Idle. The panel opens beside the desktop pet. Petoken never stores keystroke content or persistently saves media subtitle text.",
    "settings_save_error": "Could not save settings. Check write permission for your user folder.",
    "scope_global": "Global", "scope_global_recorded": "Global (Locally Recorded)",
    "scope_project": "Project", "scope_conversation": "Conversation",
    "spirit_accessible": "Ice spirit", "connecting": "Connecting…",
    "collapse_expand": "Collapse / expand", "hide_to_tray": "Hide to system tray",
    "waiting_codex": "Waiting for a task", "open_codex_task": "Open a task in Codex",
    "total_tokens": "TOTAL TOKENS", "input": "INPUT", "output": "OUTPUT",
    "switch_scope": "Switch usage scope", "analytics_button": "Token Analytics  ↗",
    "analytics_button_tip": "Open raw usage, derived metrics, models, conversations, and history",
    "context_used": "Context used", "five_hour_limit": "5-hour limit",
    "weekly_limit": "Weekly limit", "estimated_cost": "Estimated Cost",
    "currency": "Currency", "fx_unavailable_usd": "Exchange rate unavailable; showing USD.",
    "one_usd_equals": "1 USD = {rate} {currency}",
    "partial_estimate": "Partial Estimate", "always_on_top": "Always on Top",
    "character_size": "Character Size",
    "goal_unit_million": "million tokens",
    "goal_unit_billion": "billion tokens",
    "focus_todo_note": "With a todo, its name shows beside the countdown and the end card can tick it off.",
    "focus_break_length": "Break",
    "focus_long_break_length": "Long break",
    "focus_long_break_every": "Long break every",
    "focus_rounds_suffix": " rounds",
    "focus_no_break": "No break",
    "focus_never": "Never",
    "focus_pill_todo": "{todo} · {time}",
    "focus_todo_done": "This todo is done",
    "focus_line_focused": "Focused on: {todo}",
    "preset_folder_fixed": "Folder: {folder} (the project's own folder; change it under Edit)",
    "handoff_note_heading": "Your note · {ago}",
    "handoff_delete": "Delete",
    "handoff_history": "Earlier notes",
    "handoff_history_title": "Notes for {project}",
    "handoff_history_empty": "No notes yet.",
    "handoff_history_delete": "Delete selected",
    "todo_review_notice": "Ready for your review: {title}",
    "todo_review_notice_body": "The AI is done. Select it under Todos in the workbench, see what it did, then Accept or Redo.",
    "todo_review_button": "Review…",
    "todo_review_title": "Review the AI's work",
    "todo_review_intro": "{app} finished \"{title}\". Here is what it did:",
    "todo_review_no_note": "No record was found. Open the project folder to see what changed.",
    "todo_review_feedback": "What should change? (needed for Redo)",
    "todo_review_feedback_hint": "For example: the button colour is wrong, and add tests",
    "todo_review_need_feedback": "Write what should change so the AI knows what to redo.",
    "todo_review_accept": "Accept",
    "todo_review_redo": "Redo",
    "todo_redo_marker": "My feedback on the last attempt:",
    "todo_redo_prompt": "My feedback on the last attempt: {feedback}",
    "todo_ai_badge_review": "◎ {app} done, waiting for your review",
    "wb_goal": "Usage Goal",
    "wb_goal_column": "This week / Goal",
    "goal_title": "Weekly usage goal for {project}",
    "goal_intro": "The most this project should use per week (from Monday). At 80% she gets worried, going over brings one notice, and a whole week under the goal makes her proud. Use tokens, API-equivalent dollars, or both.",
    "goal_tokens": "Tokens",
    "goal_usd": "Amount (USD)",
    "goal_none": "No limit",
    "goal_tokens_suffix": " M tokens",
    "goal_worried": "{project} has used {percent}% of this week's goal",
    "goal_over": "{project} went over this week's goal ({percent}%)",
    "goal_body": "See this week's usage under Projects in the workbench, or change the goal.",
    "goal_proud": "{project} stayed under its goal last week. Well done!",
    "wb_collection": "Collection",
    "collection_intro": "Companionship points come from todos done, AI work you accepted, focus sessions and breaks, never from how many tokens you use. Milestones earn stickers.",
    "collection_points": "Companionship points: {points}",
    "collection_log": "Recent points",
    "collection_log_line": "{when}  {reason}  +{points}",
    "collection_empty": "No points yet. Finish a todo or a focus session.",
    "points_todo_done": "Todo done",
    "points_todo_accepted": "Accepted the AI's work",
    "points_focus_done": "Focus session done",
    "points_break_taken": "Took the break",
    "points_goal_week": "A week under the usage goal",
    "sticker_earned": "New sticker: {name}",
    "sticker_earned_on": "Earned {date}",
    "sticker_locked": "Not yet",
    "sticker_first_project": "First Project",
    "sticker_first_project_how": "Finish a todo that belongs to a project.",
    "sticker_first_weekly": "First Weekly",
    "sticker_first_weekly_how": "Open This Week in Reports for the first time.",
    "sticker_focus_10": "Ten Focus",
    "sticker_focus_10_how": "Finish 10 focus sessions.",
    "sticker_streak_7": "Seven Days",
    "sticker_streak_7_how": "Finish at least one focus session a day, 7 days in a row.",
    "sticker_goal_week": "Goal Keeper",
    "sticker_goal_week_how": "Keep a project under its usage goal for a whole week.",
    "sticker_todos_100": "100 Todos",
    "sticker_todos_100_how": "Finish 100 todos in all.",
    "preset_title": "Start settings for {project}",
    "preset_prompt": "Opening prompt (empty uses the default: look at the project and where we left off)",
    "preset_default_prompt": "Look at the current state of this project, tell me where we left off and what to do next, and wait for my go-ahead before changing anything.",
    "preset_handoff_line": "My note from last time: {note}",
    "preset_note": "Start Work opens a terminal with these settings; your latest \"where to continue\" note is added to the prompt.",
    "preset_save": "Save",
    "preset_start": "Start Work",
    "preset_need_folder": "This project has no folder yet. Choose one under Edit first.",
    "wb_preset": "Start Settings",
    "wb_continuation": "Where I Left Off",
    "handoff_title": "Back to {project} · where you left off",
    "handoff_note": "Your note: {note}",
    "handoff_last_task": "Last {app} task: {title} ({ago})",
    "handoff_unfinished": "Given to AI but not finished: {names}",
    "handoff_todos": "{count} open todos: {names}",
    "handoff_md": "The project's HANDOFF.md:",
    "handoff_placeholder": "Leave yourself a note: where to continue…",
    "handoff_save": "Save",
    "handoff_saved": "Saved. She will remind you next time.",
    "handoff_empty": "Nothing to show for this project yet: no notes, todos or recent tasks.",
    "ago_minutes": "{n} min ago",
    "ago_hours": "{n} h ago",
    "ago_days": "{n} days ago",
    "continuation_setting": "Remind me where I left off",
    "continuation_setting_tip": "When you come back to a project after a while, she holds up a card with where you left off.",
    "focus_menu": "Focus",
    "focus_minutes": "{minutes} min",
    "focus_hours": "{hours} h {minutes} min",
    "focus_custom": "Choose a todo and breaks…",
    "focus_stop": "End focus ({time} left)",
    "focus_skip_break": "Skip break",
    "focus_pill": "Focus · {time}",
    "focus_pill_break": "Break · {time}",
    "focus_start_title": "Start focusing",
    "focus_start_intro": "While you focus she keeps you company quietly. Only urgent notices pop up (approvals, failures, quota and full context); the rest are kept under Notifications.",
    "focus_length": "Length",
    "focus_minute_suffix": " min",
    "focus_project": "Project",
    "focus_todo": "Focus on a todo (optional)",
    "focus_no_project": "No project",
    "focus_no_todo": "None",
    "focus_start": "Start",
    "focus_done_title": "Focus done · {time}",
    "focus_stopped_title": "Focus ended · {time}",
    "focus_line_todos": "{count} todos done: {names}",
    "focus_line_ai": "AI finished {count} tasks",
    "focus_line_files": "{count} files changed",
    "focus_line_tokens": "{tokens} used",
    "focus_line_none": "No todos or AI tasks were recorded in this time.",
    "focus_counting": "Counting files and usage…",
    "focus_break_note": "Take a {minutes}-minute break now: stand up, have some water.",
    "focus_again": "Focus again",
    "focus_card_close": "OK",
    "focus_break": "Focus done: take a {minutes}-minute break",
    "focus_break_body": "Stand up, have some water. She will wait for you.",
    "focus_break_over": "Break is over",
    "focus_break_over_body": "Right-click her to start another focus session.",
    "report_focus": "Focused {count} times, {time} in all",
    "clinginess": "Clinginess",
    "clinginess_quiet": "Quiet",
    "clinginess_moderate": "Moderate",
    "clinginess_clingy": "Clingy",
    "clinginess_tip": "How often she does things by herself: Quiet only falls asleep and wakes up; Moderate sometimes daydreams, yawns and greets you; Clingy does it more, peeks at you and acts cute for attention.",
    "star_ring_enabled": "Show star ring and task Stars",
    "panel_pin": "Pin panel open", "panel_unpin": "Unpin panel",
    "checking_wait": "Checking every second · Waiting for data", "settings_help": "Settings and data notes",
    "tray_tip": "petoken · Double-click to show", "show_hide": "Show / hide",
    "show_hide_pet": "Show / hide desktop pet", "move_right": "Move to right side of screen",
    "exit_petoken": "Exit petoken", "settings_save_failed": "Settings could not be saved",
    "mode_follow": "● Following automatically", "mode_fixed": "◇ Pinned task", "mode_working": "● Working conversation",
    "mode_recent": "◌ Recently active · Foreground unknown", "waiting_data": "Waiting for data",
    "task_detection_tip": "The current task is identified from the Codex window accessibility title, or from the Claude Code session registry. If unavailable, the app explicitly falls back to recent activity; a task can also be pinned in Settings.",
    "waiting_available_task": "Waiting for an available task", "active_session": "Active session", "unnamed_task": "Untitled task",
    "model_not_recorded": "Model not recorded",
    "model_tip": "The most recently submitted model configuration. Menu changes may not be recorded until a message is sent.",
    "effort_tip": "Reasoning effort · Most recently submitted configuration",
    "no_reliable_record": "N/A · No reliable record", "cached_input_line": "Cached input: {value}",
    "output_includes_reasoning": "Reasoning output is already included and is not added again.",
    "context_tip": "Current task · {used} / {window} Tokens\nLatest recorded context use, not cumulative Tokens; it may differ slightly from the CLI reserved-space calculation.",
    "cache_hit_new_work": "Cache hit {ratio}  ·  New work {work}",
    "local_conversations": "{scope} · {count} local conversations",
    "known_price_usd": "Known-price portion USD ${usd}",
    "not_subscription_bill": "This is not a subscription bill. It converts recorded model and service-tier usage and excludes tool fees.",
    "unpriced_models": "No price for: {models} (add one in Settings)",
    "partial_records": "Some records are missing or reset, or inherited fork history was excluded.",
    "quota_unavailable": "This limit is unavailable for the current account.", "unknown": "Unknown",
    "account_quota": "Account limit · Remaining percentage", "reset_time": "Reset time: {reset}",
    "quota_stale": "Last recorded value; waiting to refresh", "quota_live": "Official endpoint · Queried every second",
    "left": "left", "stale": "stale", "awaiting_reset": "Waiting for the server to confirm reset",
    "reset_in": "Reset in {duration}", "quota_waiting": "Waiting for limit refresh", "quota_not_provided": "No limits from this source",
    "wb_notifications": "Notifications",
    "wb_notify_intro": "Finished, failed and waiting tasks, low limits and your reminders are kept here for 30 days. Double-click a waiting-for-approval item to open its task.",
    "wb_notify_open_hint": "Double-click to open this task",
    "wb_add_todo": "Add todo",
    "wb_todo_content": "Content",
    "wb_add_reminder": "Add reminder",
    "wb_reminder_repeat": "Repeat",
    "wb_reminder_time": "Time",
    "wb_reminder_todo": "Linked todo",
    "wb_reminder_empty": "Write what to be reminded of first.",
    "wb_notify_all": "All",
    "wb_notify_empty": "No notifications yet.",
    "notify_kind_finished": "Finished",
    "notify_kind_failed": "Error",
    "notify_kind_needs_approval": "Waiting for approval",
    "notify_kind_quota_low": "Low limit",
    "notify_kind_reminder": "Reminder",
    "notify_kind_forecast": "Limit forecast",
    "notify_kind_context_full": "Context almost full",
    "notify_kind_stuck": "Maybe stuck",
    "notify_kind_quota_back": "Limit back",
    "notify_forecast": "{provider}: 5-hour limit runs out in about {time}",
    "notify_forecast_switch": "{other} still has plenty left: switch there for now",
    "notify_context_full": "{provider}: context almost full",
    "notify_context_full_body": "{left}% left: run /compact or start a new conversation",
    "notify_stuck": "{provider}: no progress for {minutes} minutes",
    "notify_quota_back": "{provider}: limit is back, you can continue",
    "approval_setting": "Approve Claude on the pet",
    "approval_setting_tip": "When Claude Code asks for permission (run a command, edit a file…), a card appears beside the pet: Allow, Always allow, Deny, or hand it back to Claude. If you do not answer within {wait} seconds, or Petoken is not running, Claude Code asks you itself as usual. Adds one hook to Claude Code's settings (backed up first); turning this off removes only that hook.",
    "approval_rules": "Allowed rules…",
    "approval_rules_title": "Always-allow rules",
    "approval_rules_intro": "Rules Claude Code saved in each project's .claude/settings.local.json when you chose Always allow on the pet. Revoke one and Claude Code asks again next time.",
    "approval_rules_empty": "No rules yet.",
    "approval_revoke": "Revoke",
    "approval_rules_close": "Close",
    "approval_title_shell": "{provider} wants to run a command",
    "approval_title_edit": "{provider} wants to edit a file",
    "approval_title_web": "{provider} wants to go online",
    "approval_title_tool": "{provider} wants to use {tool}",
    "approval_project": "Project: {project}",
    "plan_title": "{provider} has a plan",
    "plan_open": "Open the plan file",
    "plan_feedback": "What should change? (optional, sent with Revise)",
    "plan_revise": "Revise",
    "plan_accept": "Accept",
    "plan_accept_edits": "Accept, allow edits",
    "plan_accept_edits_tip": "Accept the plan and stop asking about file edits for this session (same as in Claude).",
    "question_title": "{provider} has a question for you",
    "question_other": "Or type your own answer",
    "question_multi": "Multiple-choice questions allow several answers.",
    "question_submit": "Answer",
    "question_countdown": "Back to Claude in {time}",
    "approval_allow": "Allow",
    "approval_always": "Always allow",
    "approval_deny": "Deny",
    "approval_ask": "Answer in Claude",
    "approval_countdown": "Back to Claude in {seconds}s",
    "approval_more": "{count} more",
    "approval_always_tip": "Never ask again in \u201c{project}\u201d: {rule}",
    "approval_always_unavailable": "Too long or multi-line: allow once only",
    "recap_files": "{count} files changed",
    "recap_no_files": "no files changed",
    "launch_menu": "Quick launch…",
    "launch_chat": "Just chat (no project work)",
    "launch_chat_tip": "No folder needed: a conversation opens in an empty folder of Petoken's own, for questions and ideas; your project files are not touched.",
    "launch_model": "Model",
    "launch_effort": "Effort",
    "launch_model_default": "Default (the app's own setting)",
    "launch_effort_default": "Default (the app's own setting)",
    "launch_options_unavailable": "For now this app uses only its own default",
    "launch_effort_none": "This model has no effort setting",
    "launch_model_credits_badge": "Requires usage credits",
    "launch_bad_choice": "The app does not offer this model and effort together; choose another.",
    "launch_title": "Quick launch",
    "launch_prompt": "What should it do?",
    "launch_prompt_hint": "e.g. Add a dark mode to the website",
    "launch_folder": "Project folder",
    "launch_browse": "Browse…",
    "launch_app_missing": "This app's command-line tool was not found (install the Claude Code or Codex CLI)",
    "launch_note": "Starts in a new terminal and asks for permissions as usual; it then shows up as a star.",
    "launch_cancel": "Cancel",
    "launch_start": "Start",
    "launch_need_prompt": "Write what it should do first.",
    "launch_need_folder": "Choose a project folder that exists.",
    "launch_too_long": "Too long for a Windows command line: please shorten it.",
    "launch_failed": "Could not open a terminal.",
    "launch_hotkey": "Quick launch shortcut",
    "launch_hotkey_tip": "Press {combo} anywhere to open quick launch: write what to do, pick the project and app, and it starts in a new terminal. Also in the pet's right-click menu and the tray menu.",
    "launch_hotkey_taken": "{combo} and the other choices are taken by other programs: use the right-click menu instead.",
    "launch_hotkey_moved": "{combo} is taken by another program; {active} is used instead.",
    "launch_hotkey_off": "Off",
    "wb_reports": "Reports",
    "report_intro": "How much AI did for you today or this week: tasks finished, time worked, files changed, usage and cost. All from this computer; cost is the API-equivalent estimate, not a subscription bill.",
    "report_today": "Today",
    "report_week": "This week",
    "report_reload": "Recount",
    "report_loading": "Counting…",
    "report_updating": "Updating…",
    "report_updated": "Updated {time}",
    "report_tile_tasks": "Tasks worked on",
    "report_tile_time": "AI working time",
    "report_tile_files": "Files changed",
    "report_tile_time_tip": "Sum of each Claude Code and Codex turn, from your prompt to the last reply (parallel tasks add up).",
    "report_tile_files_tip": "Files Claude Code and Codex changed successfully. Files changed by shell scripts are not counted.",
    "report_tile_tokens": "Tokens",
    "report_tile_cost": "API-equivalent cost",
    "report_tile_change": "Usage vs last period",
    "report_outcomes": "Outcomes Petoken saw: {finished} finished, {failed} failed",
    "report_cost_note": "API-equivalent estimate, not a subscription bill.",
    "report_cost_partial": "Some responses use a model without a known price and are not included, so the real figure is higher.",
    "report_provider_line": "{app}: {tasks} tasks · {tokens} · {cost}",
    "report_projects": "Busiest projects: {projects}",
    "report_missing": "Could not read: {apps}",
    "report_empty": "Nothing recorded in this period yet.",
    "report_history": "Task history",
    "report_search": "Search titles or projects",
    "report_range_week": "Last 7 days",
    "report_range_month": "Last 30 days",
    "report_range_all": "All",
    "report_col_when": "When",
    "report_col_app": "App",
    "report_col_title": "Title",
    "report_col_project": "Project",
    "report_col_tokens": "Tokens",
    "report_col_cost": "Cost",
    "update_setting": "Updates",
    "update_check": "Check daily",
    "update_auto_short": "Install automatically",
    "update_check_now": "Check now",
    "update_tip": "Once a day Petoken reads the latest version from GitHub (nothing about this computer is sent). When there is a new one it shows what changed; with Install automatically it downloads, verifies the checksum and installs while no task is running, then reopens. Settings and data are kept.",
    "update_title": "Petoken {version} is available",
    "update_heading": "Version {version} is out (you have {current}). What's new:",
    "update_no_notes": "This version has no release notes.",
    "update_auto": "Update automatically from now on (while no task is running)",
    "update_skip": "Skip this version",
    "update_later": "Later",
    "update_now": "Update now",
    "update_downloading": "Downloading and verifying; Petoken will then close, install and reopen…",
    "update_failed": "The update did not finish; your current version is unchanged",
    "update_none": "You have the latest version ({version})",
    "update_check_failed": "Could not reach GitHub; try again later",
    "onboarding_setting": "Welcome guide",
    "onboarding_open": "Open again…",
    "onboard_welcome_title": "Welcome to Petoken",
    "onboard_welcome_body": "Petoken is an AI coding companion that lives on your desktop: it follows your Codex and Claude Code tasks, shows usage, limits and cost, tells you when a task finishes or needs you, and lets you answer Claude right beside the character. Take a minute to turn on what you need. Everything stays on this computer.",
    "onboard_claude_title": "Claude Code",
    "onboard_claude_body": "Claude Code is installed. These features change Claude Code's settings file (backed up first; your own settings are kept). You can turn each off later in Settings > Claude.",
    "onboard_claude_sync": "Sync Claude usage",
    "onboard_claude_sync_note": "Adds a status-line command so Pro/Max 5-hour and weekly limits show up. Keeps only usage numbers.",
    "onboard_claude_notify": "Claude instant notifications",
    "onboard_claude_notify_note": "Adds a few hooks: hear within a second when a task finishes, fails or waits for you. Keeps only event types and times.",
    "onboard_claude_approval": "Approve Claude on the pet",
    "onboard_claude_approval_note": "Permission requests, questions and plans appear as cards beside the character. With Petoken closed nothing changes.",
    "onboard_mute_claude_toasts": "Mute the Claude app's pop-ups while Petoken runs",
    "onboard_mute_claude_toasts_note": "One notice instead of two; your setting comes back when Petoken exits.",
    "onboard_codex_title": "Codex",
    "onboard_codex_body": "Codex is installed. Its usage and limits show up without any setup; the feature below changes Codex's hooks.json (backed up first). You can turn it off later in Settings > Claude and Codex.",
    "onboard_codex_note": "Hear at once when a Codex task finishes or waits for approval, and answer approvals beside the character. Trust the hooks once in Codex with /hooks; they apply to new sessions.",
    "onboard_assistant_title": "A time-saving assistant",
    "onboard_assistant_body": "The shortcut opens quick launch anywhere: write what to do and Claude or Codex starts in a new terminal. Predictions tell you ahead of time when a limit will run out.",
    "onboard_done_title": "You're all set",
    "onboard_done_body": "Click the character for the usage panel and drag to move it; right-click for quick launch, the workbench, reports and settings. Petoken tells you when a new version is out. Open this guide again from Settings > General.",
    "onboard_tutorial": "Open the workbench tutorial next",
    "onboard_skip": "Skip",
    "onboard_back": "Back",
    "onboard_next": "Next",
    "onboard_finish": "Finish",
    "todo_ai_button": "Give to AI…",
    "todo_ai_title": "Give this todo to AI",
    "todo_ai_prompt": "What should the AI do? (the todo's title by default; be as specific as you like)",
    "todo_ai_now": "Start now",
    "todo_ai_at": "At:",
    "todo_ai_note": "At that time it starts in a new terminal and asks for permissions as usual (or on the pet). When the AI is done, a note records what it did and the todo waits for your review: it counts as done once you accept it.",
    "todo_ai_take_back": "Take back",
    "todo_ai_take_back_tip": "Stop handing this to AI: cancel the schedule or stop following the running task (an open terminal is not closed).",
    "todo_ai_lost": "{count} todos given to AI never got a task",
    "todo_ai_lost_body": "The terminal may not have started or was closed. Give the todo to AI again from Todos.",
    "todo_ai_ok": "OK",
    "todo_ai_badge_waiting": "⏰ {when} · {app}",
    "todo_ai_badge_started": "▶ {app} working",
    "todo_ai_badge_finished": "✓ {app} done (see note)",
    "todo_ai_badge_failed": "⚠ {app} failed or did not start",
    "todo_ai_badge_missed": "⏸ Missed: select it and choose Give to AI… to start",
    "todo_ai_missed": "{count} scheduled todos missed their time",
    "todo_ai_missed_body": "Petoken or the PC was off. Run or cancel them from the workbench Todos.",
    "todo_ai_note_title": "AI finished: {title}",
    "todo_ai_note_intro": "{app} finished the todo \u201c{title}\u201d.",
    "todo_ai_note_prompt": "Asked: {prompt}",
    "todo_ai_note_folder": "Folder: {folder}",
    "todo_ai_note_summary": "Recap: {summary}",
    "todo_ai_note_files": "Files changed:",
    "todo_ai_note_check": "Check that the result is what you wanted; give the todo to the AI again if not.",
    "schedule_missed": "Missed scheduled todos",
    "schedule_missed_ask": "Remind me next time",
    "schedule_missed_run": "Run them right away",
    "schedule_missed_tip": "When Petoken or the PC was off at the scheduled time: remind you to decide, or start as soon as Petoken opens.",
    "codex_hooks": "Codex instant notifications and approvals",
    "codex_hooks_tip": "Adds a few hooks to Codex's hooks.json (backed up first; your own hooks are kept): hear at once when a Codex task finishes or waits for approval, and answer approvals beside the character (allow once or deny). Codex asks you to trust these hooks once with /hooks; they apply to new sessions. With Petoken closed Codex asks as usual.",
    "menu_more": "More",
    "diagnostics_export": "Export diagnostics…",
    "diagnostics_tip": "Save a zip to attach to a GitHub issue when something goes wrong. You see everything in it before saving.",
    "diagnostics_intro": "This is everything that goes into the zip: versions, which features are on, the error log, the approval step log and notification counts for the last 7 days. No conversation or file contents, commands, folder paths or account details. Check it, then choose Save.",
    "diagnostics_saved": "Saved to {path}",
    "diagnostics_failed": "Could not save there; try another place.",
    "mute_claude_toasts": "Mute the Claude app's pop-ups while Petoken runs",
    "mute_claude_toasts_tip": "Avoids double pop-ups: while Petoken runs, the Claude desktop app's own Windows notifications are off (the same switch as Windows Settings > System > Notifications > Claude). Your previous setting comes back when Petoken exits or you untick this. No administrator rights needed.",
    "settings_page_general": "General",
    "settings_page_tracking": "Tasks",
    "settings_page_claude": "Claude and Codex",
    "settings_page_assistant": "Assistant",
    "settings_page_about": "About the data",
    "assistant_hints": "Predictions and tips",
    "assistant_hints_tip": "At your current pace, predicts when limits run out, suggests switching to the app with more left, and tells you when context is almost full, a task makes no progress for a while, or a used-up limit is back. All computed on this computer.",
    "hint_out": "Limit used up until it resets",
    "hint_out_switch": "Limit used up · use {other} for now",
    "hint_run_out": "At this pace, out in about {time}",
    "hint_run_out_switch": "Out in ~{time} · switch to {other}?",
    "hint_context_full": "{left}% context left · try /compact",
    "hint_week_run_out": "Weekly limit out in about {time}",
    "hint_stuck": "No progress for {minutes} min",
    "wb_reminders": "Personal reminders",
    "wb_reminder_placeholder": "Reminder, e.g. check the Codex result",
    "wb_repeat_once": "Once",
    "wb_repeat_daily": "Daily",
    "wb_repeat_weekly": "Weekly",
    "wb_reminder_no_todo": "No linked todo",
    "wb_reminder_past": "That time has already passed; choose a later one.",
    "wb_reminder_done": "done",
    "wb_every_day": "Daily {time}",
    "wb_every_week": "Every {day} {time}",
    "wb_weekday_names": "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
    "claude_notify": "Claude instant notifications",
    "claude_notify_tip": "Adds a few hooks to Claude Code's settings so Petoken tells you at once when Claude finishes, hits an error or waits for your approval (CLI and desktop app). Only event types and times are kept, never conversation content. Your settings are backed up first, and turning this off removes only Petoken's hooks. When off, finished tasks are still noticed by regular checks, a few seconds later.\nTip: the Claude desktop app shows its own completion notice too; tick “Mute the Claude app's pop-ups while Petoken runs” below to get only Petoken's.",
    "dnd": "Do Not Disturb",
    "dnd_scheduled": "Scheduled quiet hours",
    "dnd_tip": "While quiet, no pop-ups and no pet reactions; notifications are still listed under Notifications in the workbench.",
    "notify_finished": "{provider} task finished",
    "notify_failed": "{provider} task hit an error",
    "notify_needs_approval": "{provider} is waiting for your approval",
    "notify_quota_low": "{provider}: {left}% of the 5-hour limit left",
    "notify_reminder": "Reminder",
    "usage_context": "Ctx",
    "usage_five_hour": "5h",
    "usage_week": "Week",
    "usage_remaining": "left",
    "usage_quota_unknown": "No limit data yet",
    "usage_quota_waiting_codex": "Reading limits…",
    "usage_claude_sync_on": "Limits appear after the next reply",
    "usage_claude_sync_off": "Turn on Sync Claude usage in Settings",
    "claude_usage_sync": "Sync Claude usage",
    "claude_usage_sync_tip": "Adds a status-line command to Claude Code's settings so Petoken can show the 5-hour and weekly usage and context. Only numbers are kept, never conversation content. Needs Claude Pro/Max. Your settings are backed up first, and turning this off removes the command.",
    "claude_usage_sync_foreign": "Claude Code already has a custom status line; Petoken will not replace it.",
    "claude_usage_sync_unreadable": "Claude Code's settings file could not be read, so nothing was changed.",
    "claude_quota_updated": "Claude usage · updated {time} (syncs when Claude Code replies)",
    "claude_quota_waiting": "Claude usage sync is on · waiting for Claude Code's next reply (Pro/Max)",
    "claude_quota_off": "Claude usage not synced · turn it on in Settings",
    "compat_partial": "Partly compatible", "compat_unsupported": "Format not recognized",
    "compat_partial_tip": "Some Codex local data structures were not recognized: those numbers show N/A, the rest is unaffected.",
    "compat_unsupported_tip": "The Codex local data format is not recognized (likely a Codex update); usage is unavailable for now.",
    "compat_version": "Codex version: {version}",
    "syncing": "Syncing every second · {time}", "token_last_written": "Token last written {seconds} seconds ago",
    "no_token_events": "No Token events yet", "no_model_usage": "Reading local data does not call a model or consume model Tokens.",
    "quota_error": "Limits are temporarily unavailable; keeping the last value and retrying later.",
    "manual": "Manual", "custom": "Custom",
    "pet_title": "petoken · Skirk Desktop Pet",
    "pet_accessible": "Skirk desktop pet. Click to view usage, drag to move, or right-click for the menu.",
    "project_unavailable": "Project unavailable", "codex_working": "Codex Working", "claude_working": "Claude Code Working",
    "pet_tooltip_tokens": "Total {total} · Input {input} · Output {output}",
    "pet_tooltip_actions": "Click to view usage · Drag to move · Right-click for menu",
    "working": "Working", "idle": "Idle", "context_short": "Ctx",
    "pet_toggle_panel": "Open / collapse usage panel", "pet_settings": "Settings and task selection",
    "idle_motion": "Idle motion", "hide_pet": "Hide desktop pet (restore from tray)", "exit": "Exit",
    "analytics_title": "petoken · Token Analytics", "analytics_heading": "TOKEN ANALYTICS · {scope}",
    "tab_full": "Full Usage", "tab_models": "By Model", "tab_conversations": "By Conversation",
    "tab_history": "Date && History", "tab_raw": "Raw Fields / Source",
    "header_group_metric": "Group / Metric", "header_exact": "Exact Value", "header_type_coverage": "Type / Coverage",
    "header_model": "Model", "header_conversation": "Conversation", "header_range": "Range",
    "header_date_local": "Date / Local Time", "records": "Records",
    "fx_rate_label": "1 USD = CAD",
    "header_input_tokens": "Input Tokens", "header_cached_tokens": "Cached Tokens",
    "header_uncached_tokens": "Uncached Tokens", "header_write_tokens": "Write Tokens",
    "header_output_tokens": "Output Tokens", "header_reasoning_tokens": "Reasoning Tokens",
    "header_nonreasoning_tokens": "Non-reasoning Tokens", "header_total_tokens": "Total Tokens",
    "analytics_subtitle": "{title} · {project} · {events:,} Records\nModels, conversations, dates, and history use the current scope. Global represents locally readable records only.",
    "history_initial": "Local indexed history · System local time; includes archived conversations. This is not complete server-account lifetime usage.",
    "history_loaded": "Local indexed history · Local time / calendar days · Excludes deleted, cloud-only, or unsynced records.",
    "history_partial": " Missing or excluded inherited history makes this a partial record.",
    "history_loading": "Reading local history incrementally…",
    "analytics_na_note": "N/A = reliable data is unavailable. Hover for formulas and exact sources; supported subtotals are shown separately.",
    "analytics_default_note": "Cached input and reasoning are subsets and are not added to Total again.",
    "raw": "raw", "derived": "derived", "known_subtotal": "known subtotal {value}",
    "total_source_coverage": "source total; falls back only to input + output when missing",
    "range_current": "Current session", "range_lifetime": "Local recorded lifetime", "range_today": "Today",
    "range_last7": "Last 7 calendar days", "range_last30": "Last 30 calendar days", "range_undated": "Undated / unallocated",
    "group_official": "Official OpenAI Usage", "group_cache": "Cache", "group_derived": "Derived Analytics", "group_comparison": "Comparison",
    "metric_total": "Total Tokens", "metric_input": "Input Tokens", "metric_cached": "Cached Input / Cache Read",
    "metric_uncached": "Uncached Input", "metric_output": "Output Tokens", "metric_reasoning": "Reasoning Tokens",
    "metric_nonreasoning": "Non-reasoning Output", "metric_cache_write": "Cache Write", "metric_cache_hit": "Cache Hit Ratio",
    "metric_new_work": "New / Non-cached Work", "metric_output_ratio": "Output Ratio", "metric_reasoning_ratio": "Reasoning Share of Output",
    "metric_comparison_uncached": "Input excluding cache read AND write", "metric_cache_read_component": "Cache Read component",
    "metric_cache_write_component": "Cache Write component", "metric_output_component": "Output component",
    "metric_claude_raw": "Claude-style Raw Processed", "metric_known_processed": "Supported processed subtotal",
    "unknown_model": "Unknown / Not recorded", "unknown_breakdown": "Unknown / missing Token breakdown",
    "raw_field_notes": "Unknown extra source fields are preserved here but are not interpreted or added to totals.",
    "help_total_tokens": "Official OpenAI total where available; otherwise input + output. Cached input is already inside input, and reasoning is already inside output.",
    "help_total_tokens_claude": "Claude Code: total = input + output. Input already includes cache reads and writes; thinking tokens are already inside output.",
    "help_input_tokens": "Source input_tokens. Includes cached input and any reported cache-write input.",
    "help_cached_input_tokens": "Previously processed input reused from cache; a subset of input_tokens.",
    "help_uncached_input_tokens": "max(input − cached, 0). Input not served from cache; includes cache writes if reported.",
    "help_cache_write_input_tokens": "Source cache_write_input_tokens / cache_write_tokens only. Missing = N/A, not zero. A reported 0 is displayed as 0.",
    "help_output_tokens": "Source output_tokens. Already includes reasoning output.",
    "help_reasoning_output_tokens": "Reasoning Tokens reported as part of output usage; not added again to total.",
    "help_non_reasoning_output_tokens": "max(output − reasoning, 0).",
    "help_new_work": "Uncached input + output. Useful for separating newly processed work from repeated cached context.",
    "help_cache_hit_ratio": "cached ÷ input × 100. N/A if input is zero or a required field is missing.",
    "help_output_ratio": "output ÷ official total × 100. N/A if total is zero.",
    "help_reasoning_ratio": "reasoning ÷ output × 100. N/A if output is zero or reasoning is missing.",
    "help_comparison_uncached": "Comparison component: input − cache read − cache write. Writes are removed so the four components do not overlap.",
    "help_claude_raw": "Comparison only, not the official total. Non-cache/non-write input + cache read + cache write + output. OpenAI and Claude expose caching differently, so their headline totals should not be compared blindly. N/A when a component is unavailable.",
    "help_known_processed": "Supported subtotal: uncached input + cache read + output. Does not invent a cache-write split or add unknown writes.",
    "status_no_local_data": "No local Codex data found. Open a task in the client first.",
    "status_database_unavailable": "The Codex database is temporarily unreadable. Retrying next second.",
    "status_pinned_unavailable": "The pinned task is unavailable. Select it again.",
    "status_no_desktop_task": "No local desktop task is available yet.", "status_project_unavailable": "The current conversation has no reliable project identity.",
    "status_no_usage": "No local usage records are available yet.", "status_read_failed": "Reading temporarily failed. Retrying next second.",
    "display_all_usage": "All usage", "display_local_history": "Locally recorded history", "display_untitled": "Untitled conversation",
    "note_reset_missing_last": "Counter reset without a last-request record; the increment is unavailable.",
    "note_reset_used_last": "Cumulative counter reset: counted explicit last-request usage instead of the reset snapshot.",
    "note_reset_carry": "The reset snapshot contains untraceable carry; it was not added to avoid duplication.",
    "note_initial_carry": "The first snapshot contains earlier usage without timestamps or model; retained as unattributed carry.",
    "note_cache_write_unavailable": "Cache-write split is unavailable; cost excludes any unknown write premium.",
    "tracking_provider": "Tracking provider", "tracking_auto": "Auto", "tracking_codex": "Codex",
    "tracking_opencode": "OpenCode", "status_stale": "Stale",
    "tracking_claude": "Claude Code",
    "status_claude_no_local_data": "No local Claude Code data found. Start a session in Claude Code first.",
    "analytics_provider_pending": "The current provider is OpenCode; analytics support arrives in a later update.",
    "analytics_heading_provider": "TOKEN ANALYTICS · {provider} · {scope}",
    "analytics_subtitle_opencode": "{title} · {project} · {count} local sessions · {freshness}",
    "group_opencode_raw": "OpenCode raw",
    "metric_recorded_cost": "Recorded Cost",
    "coverage_complete": "complete", "coverage_partial": "partial",
    "coverage_unknown": "unknown", "coverage_unavailable": "unavailable",
    "cost_recorded": "Recorded {amount} · currency unavailable",
    "history_cached_as_of": "Cached snapshot · as of {time}",
    "history_refresh_pending": "Refresh pending — showing the stable snapshot",
    "history_skipped_rows": "{count} malformed rows skipped — partial",
    "history_unavailable": "No daily history for this scope",
    "analytics_opencode_note": "N/A = no verified meaning. OpenCode shows raw categories plus a recorded Total for verified versions (not billing, not context); cost is a recorded amount with unknown currency.",
    "raw_source_opencode": "OpenCode SQLite session rollups + message metadata (no content)",
    "help_provider_analytics": "Analytics describes the current provider and scope; changing scope clears stale data at once.",
    "help_recorded_cost": "Sum of recorded session amounts; sessions without amounts are excluded; currency unknown.",
    "help_unknown_currency": "The source has no currency field; amounts are never converted or labelled with a symbol.",
    "help_opencode_total": "Total is the five-category sum only for verified versions with complete data (a recorded total, not billing or context); missing, partial, or unverified versions stay N/A.",
    "help_partial_coverage": "Some sessions lack this category; only the known subtotal is shown and marked partial.",
    "help_cached_history": "Daily history aggregates message metadata; cached snapshots carry as_of and stay stable while pending.",
    "opencode_cost_tip": "Recorded {amount} · currency unstated, shown as N/A",
    "opencode_model_tip": "Provider {provider} · variant {variant} · agent {agent}",
    "total_unavailable_note": "OpenCode recorded Total: the five-category sum for verified versions; not a billed amount or current context size, N/A when unavailable",
    "provider_mode_auto": "Provider: Auto",
    "provider_mode_manual": "Provider: Manual · {provider}",
    "task_panel_label": "Active task {n}",
    "task_panel_total": "Total",
    "task_panel_input": "Input",
    "task_panel_output": "Output",
    "task_panel_reasoning": "Reasoning",
    "task_panel_cache_read": "Cache Read",
    "task_panel_cache_write": "Cache Write",
    "task_panel_model": "Model",
    "task_panel_cost": "Recorded cost",
    "task_panel_effort": "Reasoning effort",
    "task_panel_variant": "Model variant",
    "task_panel_context": "Context",
    "task_collapse": "Collapse task details",
    "task_go_to_window": "Go to this task's window",
    "task_accessible": "{label} · {provider} · Press Enter for details",
    "usage_panel": "Usage panel (always shown)",
    "panel_pinned_help": "When checked, the usage panel stays open and on top instead of hiding; uncheck it to show the panel on hover again. It starts unchecked every time Petoken opens.",
    "close_unpins_hub": "Close the usage panel (also stops keeping it open)",
    "task_overview": "Active tasks · {count}",
    "task_metric_scope": "Usage: {provider} · {scope}",
    "task_source_unavailable": "Usage source unavailable; known records may be incomplete.",
    "task_usage_unavailable": "No verified usage available.",
    "task_record_note": "Records have limitations; only known usage is shown.",
    "reset_task_layout": "Reset task layout",
}

ZH_CN.update({
    'workbench_open': '打开工作台',
    'wb_heading': '你的小天地', 'wb_subtitle': '记下生活的小事，也留好工作里的下一步。',
    'wb_spaces': '项目空间', 'wb_local': '保存在此设备',
    'wb_all': '全部项目', 'wb_inbox': '未分类',
    'wb_home': '首页', 'wb_todos': '待办', 'wb_notes': '便签', 'wb_projects': '项目',
    'wb_next': '接下来做什么', 'wb_codex_tasks': '当前任务',
    'wb_summary': '{projects} 个项目    ·    {todos} 项待办    ·    {notes} 张便签',
    'wb_empty_todos': '暂时没有待办，给下一步留个位置。',
    'wb_empty_tasks': '当前没有 Codex 或 Claude Code 任务。任务出现后会显示在这里。',
    'wb_empty_notes': '新建或选择一张便签，记下你的想法。',
    'wb_empty_projects': '还没有项目。创建一个空间，把相关事项放在一起。',
    'wb_details': '查看详情', 'wb_link': '关联项目',
    'wb_todo_intro': '勾选完成，也可以随时重新打开。',
    'wb_add': '添加', 'wb_completed': '显示已完成', 'wb_edit': '编辑', 'wb_delete': '删除',
    'wb_todo_placeholder': '下一件想做的事…',
    'wb_new_note': '新建便签', 'wb_save': '保存 · Ctrl+S',
    'wb_note_title': '便签标题', 'wb_note_body': '写点什么…', 'wb_untitled': '未命名便签',
    'wb_unsaved': '未保存 · 切换或关闭前会提醒你', 'wb_saved': '已保存到此设备',
    'wb_projects_intro': '每个项目有自己的待办和便签，也可以关联 Codex 或 Claude Code 任务。',
    'wb_new_project': '新建项目', 'wb_name': '名称', 'wb_project': '项目',
    'wb_folder': '文件夹（可选）', 'wb_folder_open': '打开文件夹', 'wb_browse': '选择',
    'wb_error': '操作未完成。请检查输入或稍后重试；尚未保存的内容已保留。',
    'wb_open_error': '无法打开工作台。数据文件可能被占用或格式不受支持；原文件未被替换。',
    'wb_folder_error': '无法打开文件夹，请检查项目中的路径。',
    'wb_save_confirm': '便签尚未保存，是否保存更改？',
    'wb_delete_confirm': '删除这项待办？此操作无法撤销。',
    'wb_delete_note_confirm': '删除这张便签及尚未保存的编辑？此操作无法撤销。',
    'wb_delete_project_confirm': '删除这个项目？待办和便签会保留在「未分类」中，关联的任务不会被删除。',
})
EN.update({
    'workbench_open': 'Open workbench',
    'wb_heading': 'Your little corner', 'wb_subtitle': 'Everyday notes and your next small step, together.',
    'wb_spaces': 'Project spaces', 'wb_local': 'Saved on this device',
    'wb_all': 'All projects', 'wb_inbox': 'Unassigned',
    'wb_home': 'Home', 'wb_todos': 'Todos', 'wb_notes': 'Notes', 'wb_projects': 'Projects',
    'wb_next': 'Up next', 'wb_codex_tasks': 'Current tasks',
    'wb_summary': '{projects} projects    ·    {todos} pending    ·    {notes} notes',
    'wb_empty_todos': 'Nothing pending. Make room for your next step.',
    'wb_empty_tasks': 'No current Codex or Claude Code tasks. They will appear here when available.',
    'wb_empty_notes': 'Create or select a note to capture an idea.',
    'wb_empty_projects': 'No projects yet. Create a space for related work.',
    'wb_details': 'View details', 'wb_link': 'Link project',
    'wb_todo_intro': 'Check off a finished task, or reopen it any time.',
    'wb_add': 'Add', 'wb_completed': 'Show completed', 'wb_edit': 'Edit', 'wb_delete': 'Delete',
    'wb_todo_placeholder': 'Your next step…',
    'wb_new_note': 'New note', 'wb_save': 'Save · Ctrl+S',
    'wb_note_title': 'Note title', 'wb_note_body': 'Write something…', 'wb_untitled': 'Untitled note',
    'wb_unsaved': 'Unsaved · you will be asked before leaving', 'wb_saved': 'Saved on this device',
    'wb_projects_intro': 'Keep todos and notes together, and link related Codex or Claude Code tasks.',
    'wb_new_project': 'New project', 'wb_name': 'Name', 'wb_project': 'Project',
    'wb_folder': 'Folder (optional)', 'wb_folder_open': 'Open folder', 'wb_browse': 'Browse',
    'wb_error': 'Could not complete the action. Check your input or try again; unsaved edits are retained.',
    'wb_open_error': 'Could not open the workbench. The file may be busy or unsupported; it has not been replaced.',
    'wb_folder_error': 'Could not open the folder. Check the project path.',
    'wb_save_confirm': 'This note has unsaved changes. Save them?',
    'wb_delete_confirm': 'Delete this todo? This cannot be undone.',
    'wb_delete_note_confirm': 'Delete this note and its unsaved edits? This cannot be undone.',
    'wb_delete_project_confirm': 'Delete this project? Todos and notes move to Unassigned. Linked tasks are kept.',
})

ZH_CN.update({
    'wb_tutorial': '新手教程', 'wb_tutorial_step': '第 {n} / 5 步',
    'wb_tutorial_skip': '跳过教程', 'wb_tutorial_back': '上一步',
    'wb_tutorial_next': '下一步', 'wb_tutorial_done': '完成教程',
    'wb_tutorial_hint': '点击操作会收起教程。工作台右上角的「新手教程」可以继续或重新查看。',
    'wb_tutorial_title_0': '和桌宠一起开始',
    'wb_tutorial_body_0': '拖动人物可以移动桌宠，右键人物或托盘图标可打开工作台、用量面板和设置。\n\n工作台用来整理项目、待办和便签。即使没有运行 Codex 或 Claude Code，也可以使用这些功能。\n\n先看看界面，或点击「下一步」跟着试一试。',
    'wb_tutorial_action_0': '先看看工作台',
    'wb_tutorial_title_1': '先给事情一个家',
    'wb_tutorial_body_1': '项目把相关的待办和便签放在一起，例如「学习」或「我的桌宠」。\n\n点击下面的按钮，填写项目名称。文件夹是可选的，方便以后打开资料。\n\n左侧选择一个项目，就能查看属于它的内容；「未分类」用来随手记录。',
    'wb_tutorial_action_1': '创建一个项目',
    'wb_tutorial_title_2': '写下下一件事',
    'wb_tutorial_body_2': '进入「待办」，输入一件想做的事，选择所属项目，然后点「添加」或按回车。\n\n做完后勾选它；需要继续时，取消勾选即可重新打开。\n\n「首页」会汇总当前项目中尚未完成的事项。',
    'wb_tutorial_action_2': '去添加待办',
    'wb_tutorial_title_3': '把想法留下来',
    'wb_tutorial_body_3': '新建便签，写一个标题和内容，点击「保存」或按 Ctrl+S。便签和待办保存在这台设备上。\n\n切换便签、项目或退出时，未保存的编辑会提示你选择保存、放弃或取消。\n\n现在试着写下一句话吧。',
    'wb_tutorial_action_3': '新建一张便签',
    'wb_tutorial_title_4': '让星星陪你工作',
    'wb_tutorial_body_4': '每颗星星对应一个当前任务：Codex 是蓝色，Claude Code 是金色。点击星星，或在首页选择任务后点「查看详情」，可以查看它的用量信息。\n\n「关联项目」可以把这个任务放进你自己的项目空间。\n\n没有任务时列表为空是正常的。使用 Codex 或 Claude Code 后，可用任务会自动出现；个人待办和便签照常使用。',
    'wb_tutorial_action_4': '看看当前任务',
})
EN.update({
    'wb_tutorial': 'Getting started', 'wb_tutorial_step': 'Step {n} of 5',
    'wb_tutorial_skip': 'Skip tutorial', 'wb_tutorial_back': 'Back',
    'wb_tutorial_next': 'Next', 'wb_tutorial_done': 'Finish',
    'wb_tutorial_hint': 'An action hides this guide. Use Getting started at the top right to resume or revisit it.',
    'wb_tutorial_title_0': 'A small place to start',
    'wb_tutorial_body_0': 'Drag the character to move your pet. Right-click the character or tray icon to open the workbench, usage panel or settings.\n\nUse the workbench for projects, todos and notes, even when Codex and Claude Code are not running.\n\nLook around, or choose Next to try the basics.',
    'wb_tutorial_action_0': 'Look around the workbench',
    'wb_tutorial_title_1': 'Give your work a home',
    'wb_tutorial_body_1': 'A project keeps related todos and notes together, such as Study or My desktop pet.\n\nChoose the button below and enter a name. A folder is optional and lets you open your materials later.\n\nSelect a project in the sidebar to filter its content. Unassigned is a place for quick captures.',
    'wb_tutorial_action_1': 'Create a project',
    'wb_tutorial_title_2': 'Write your next step',
    'wb_tutorial_body_2': 'In Todos, enter something you want to do, choose a project, then select Add or press Enter.\n\nCheck it off when done. Uncheck it to reopen it.\n\nHome collects the pending items for the selected project.',
    'wb_tutorial_action_2': 'Go to Todos',
    'wb_tutorial_title_3': 'Keep a small idea',
    'wb_tutorial_body_3': 'Create a note, write a title and some text, then select Save or press Ctrl+S. Notes and todos stay on this device.\n\nWhen you switch notes or projects, or exit, unsaved edits prompt you to Save, Discard or Cancel.\n\nTry writing one sentence.',
    'wb_tutorial_action_3': 'Create a note',
    'wb_tutorial_title_4': 'Work alongside the stars',
    'wb_tutorial_body_4': 'Each star represents a current task: blue for Codex, gold for Claude Code. Select a star, or choose a task on Home and View details, to see its available usage.\n\nLink project puts the task in your own project space.\n\nAn empty task list is normal when none are available. Codex and Claude Code tasks appear automatically; personal todos and notes still work.',
    'wb_tutorial_action_4': 'Look at current tasks',
})

STRINGS = {"zh_CN": ZH_CN, "en": EN}


def normalize_language(value):
    return value if value in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def text(key, language=DEFAULT_LANGUAGE, **values):
    language = normalize_language(language)
    template = STRINGS[language].get(key, STRINGS[DEFAULT_LANGUAGE].get(key, key))
    return template.format(**values) if values else template


def scope_text(scope, language=DEFAULT_LANGUAGE, recorded=False):
    if not isinstance(scope, str):
        scope = "conversation"
    scope = {"task": "conversation"}.get(scope, scope)
    key = "scope_global_recorded" if scope == "global" and recorded else f"scope_{scope}"
    return text(key if key in STRINGS[DEFAULT_LANGUAGE] else "scope_conversation", language)
